(()=>{
"use strict";
const API="https://zadxvmpgngwtpsmdkcod.supabase.co/functions/v1/morpheus-george-pwa";
const ASSET="./assets/pet/";
const POSES={idle:"neutral.png",blink:"blink.png",aware:"curiosity.png",attention:"concern.png",listening:"alert.png",thinking:"thinking.png",speaking:"neutral.png",success:"celebration.png",happy:"happy.png"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={session:localStorage.getItem("morpheus:session")||"",device:localStorage.getItem("morpheus:device")||"",briefing:null,topicState:{},petMode:"idle",petTimer:null,blinkTimer:null,recognition:null,answer:null,contextTopicId:null,rate:Number(localStorage.getItem("morpheus:rate")||1),voiceName:localStorage.getItem("morpheus:voice")||"",deferredInstall:null,isTauri:Boolean(window.__TAURI_INTERNALS__||window.__TAURI__),speech:{chunks:[],index:0,active:false,paused:false,onDone:null}};
if(state.isTauri)document.documentElement.classList.add("tauri");
const esc=(value="")=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const uuid=()=>crypto.randomUUID?crypto.randomUUID():"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==="x"?r:(r&3|8)).toString(16)});
async function nativeInvoke(command,args={}){try{const invoke=window.__TAURI__?.core?.invoke||window.__TAURI_INTERNALS__?.invoke;if(invoke)return await invoke(command,args)}catch(error){console.warn(error)}}
async function api(method="GET",body){const options={method,headers:{Accept:"application/json"},cache:"no-store"};if(state.session)options.headers.Authorization=`Bearer ${state.session}`;if(body){options.headers["Content-Type"]="application/json";options.body=JSON.stringify(body)}const response=await fetch(API,options);let data={};try{data=await response.json()}catch{}if(response.status===401&&body?.action!=="pair")throw Object.assign(new Error("unauthorized"),{status:401});if(!response.ok)throw Object.assign(new Error(data.error||"request_failed"),{status:response.status});return data}
function ensureDevice(){if(!state.device){state.device=uuid();localStorage.setItem("morpheus:device",state.device)}return state.device}
async function pair(code){const data=await api("POST",{action:"pair",code,deviceId:ensureDevice()});state.session=data.token;localStorage.setItem("morpheus:session",data.token);localStorage.removeItem("morpheus:pair");await loadBriefing();showApp();toast("This device is paired")}
async function migrateLegacyPair(){const old=localStorage.getItem("morpheus:pair");if(!old||state.session)return false;try{await pair(old);return true}catch{localStorage.removeItem("morpheus:pair");return false}}
async function loadBriefing(){const data=await api();state.briefing=data;state.topicState=data.topicState||{};renderAll();return data}
function showPair(message=""){stopSpeech();$("#app").classList.add("hidden");$("#pairScreen").classList.remove("hidden");$("#pairError").textContent=message;document.documentElement.classList.remove("compact-mode")}
function showApp(){$("#pairScreen").classList.add("hidden");$("#app").classList.remove("hidden");if(state.isTauri){document.documentElement.classList.add("compact-mode");nativeInvoke("collapse_companion")}else{const target=new URLSearchParams(location.search).get("open");if(["talk","briefing","history"].includes(target))switchView(target)}}
function topicStatus(id){return state.topicState[id]?.status||"unread"}
function updates(){return state.briefing?.updates||[]}
function counts(){const now=new Date(),active=updates().filter(item=>{const row=state.topicState[item.id];return !row||row.status==="unread"||(row.status==="deferred"&&(!row.deferred_until||new Date(row.deferred_until)<=now))}),needs=updates().filter(item=>item.needsGeorge&&topicStatus(item.id)!=="acknowledged"&&!(topicStatus(item.id)==="deferred"&&new Date(state.topicState[item.id].deferred_until)>now));return{updates:active.length,needs:needs.length,total:updates().length}}
function greeting(){const hour=new Date().getHours();return hour<12?"GOOD MORNING, GEORGE":hour<18?"GOOD AFTERNOON, GEORGE":"GOOD EVENING, GEORGE"}
function basePetMode(){const c=counts();return c.needs?"attention":c.updates?"aware":"idle"}
function petAlt(mode){return({attention:"Morpheus has something that needs your attention",aware:"Morpheus has new updates",listening:"Morpheus is listening",thinking:"Morpheus is thinking",speaking:"Morpheus is speaking",success:"Morpheus acknowledges you",idle:"Morpheus is calm and ready"})[mode]||"Morpheus"}
function setPet(mode=basePetMode(),temporary=0){state.petMode=mode;const src=ASSET+(POSES[mode]||POSES.idle);[["#pet","pet"],["#talkPet","pet talk-pet"],["#compactPet",""]].forEach(([selector,classes])=>{const image=$(selector);if(image){image.src=src;image.alt=petAlt(mode);if(classes)image.className=`${classes} ${mode}`}});["#petStage","#talkPetStage"].forEach(selector=>$(selector)?.classList.toggle("attention",mode==="attention"));clearTimeout(state.petTimer);if(temporary)state.petTimer=setTimeout(()=>setPet(basePetMode()),temporary)}
function scheduleBlink(){clearTimeout(state.blinkTimer);state.blinkTimer=setTimeout(()=>{if(["idle","aware"].includes(state.petMode)){setPet("blink");setTimeout(()=>setPet(basePetMode()),150)}scheduleBlink()},4200+Math.random()*3600)}
function homeCopy(){const c=counts();$("#greeting").textContent=greeting();if(c.needs){$("#homeStatus").textContent=c.needs===1?"One thing needs you.":`${c.needs} things need you.`;$("#homeSub").textContent="Everything else is moving normally."}else if(c.updates){$("#homeStatus").textContent="All moving normally.";$("#homeSub").textContent=`I have ${c.updates} update${c.updates===1?"":"s"} when you’re ready.`}else{$("#homeStatus").textContent="You’re up to date.";$("#homeSub").textContent="Nothing needs your attention right now."}$("#updateCount").textContent=c.updates;$("#needsCount").textContent=c.needs;$("#compactUpdates").textContent=c.updates;$("#compactNeeds").textContent=c.needs;$("#compactStatus").textContent=c.needs?(c.needs===1?"One thing needs you.":`${c.needs} things need you.`):"All moving normally.";setPet(basePetMode())}
function statusBadge(item){const status=topicStatus(item.id);if(status==="acknowledged")return"Got it ✓";if(status==="heard")return"Heard";if(status==="deferred")return"Later";return item.needsGeorge?"Needs you":"Update"}
function updateCard(item,detail=true){return `<article class="card ${item.needsGeorge?"needs":""}"><div class="card-top"><div><div class="project">${esc(item.project)}</div><h3>${esc(item.title)}</h3></div><span class="badge ${item.needsGeorge?"need":""}">${statusBadge(item)}</span></div><p>${esc(item.summary)}</p>${detail?`<ul class="bullets">${item.bullets.map(b=>`<li>${esc(b)}</li>`).join("")}</ul>`:""}${item.action?`<div class="ask-block"><strong>What Saad needs</strong><span>${esc(item.action)}</span></div>`:""}<div class="card-actions"><button class="button secondary small listen-topic" data-topic="${item.id}">Listen</button><button class="button secondary small acknowledge-topic" data-topic="${item.id}">${topicStatus(item.id)==="acknowledged"?"Understood ✓":"I got it"}</button></div></article>`}
function renderBriefing(){const list=updates(),needs=list.filter(item=>item.needsGeorge);$("#changedCount").textContent=`${list.length} areas`;$("#needSectionCount").textContent=`${needs.length} decisions`;$("#changedCards").innerHTML=list.map(item=>updateCard(item)).join("");$("#needsCards").innerHTML=needs.length?needs.map(item=>updateCard(item,false)).join(""):`<article class="card empty"><h3>Nothing needs you.</h3><p>I’ll surface it here when a real decision is required.</p></article>`;$("#nextCards").innerHTML=(state.briefing.next||[]).map(item=>`<article class="card next-card"><div class="next-date">${esc(item.date)}</div><div><h3>${esc(item.title)}</h3><p>${esc(item.detail)}</p></div></article>`).join("");bindTopicActions()}
function renderHistory(){const entries=updates().filter(item=>topicStatus(item.id)!=="unread").sort((a,b)=>new Date(state.topicState[b.id]?.updated_at||0)-new Date(state.topicState[a.id]?.updated_at||0));$("#historyCards").innerHTML=entries.length?entries.map(item=>{const row=state.topicState[item.id],label=row.status==="acknowledged"?"Acknowledged":row.status==="deferred"?"Moved to later":"Heard";return `<article class="card history-item"><div class="history-mark">✓</div><div><h3>${esc(item.project)}</h3><p>${label} · ${esc(item.title)}</p></div></article>`}).join(""):`<article class="card empty"><h3>Nothing here yet.</h3><p>Topics appear here after you listen or say “I got it.”</p></article>`}
function renderAll(){if(!state.briefing)return;homeCopy();renderBriefing();renderHistory()}
function bindTopicActions(){$$(".listen-topic").forEach(button=>button.onclick=()=>{const item=updates().find(row=>row.id===button.dataset.topic);if(item)speak(`${item.narration} What happens next: ${item.next}.`,item.project,()=>setTopicState(item.id,"heard"))});$$(".acknowledge-topic").forEach(button=>button.onclick=()=>setTopicState(button.dataset.topic,"acknowledged",true))}
async function setTopicState(topicId,status,celebrate=false){try{const data=await api("POST",{action:"state",topicId,status});state.topicState[topicId]=data.state;renderAll();if(celebrate){setPet("success",950);toast("Got it. Marked understood.")}}catch{toast("I couldn’t save that yet")}}
function fullBriefingText(){const needs=updates().filter(item=>item.needsGeorge);return `${state.briefing.meta.fullBriefingLead} ${updates().map(item=>`${item.project}. ${item.narration}`).join(" ")} ${needs.length?`What I need from you: ${needs.map(item=>item.action).join(" And ")}`:"Nothing needs a decision from you right now."}`}
function splitSpeech(text){return(text.replace(/\s+/g," ").match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[text]).flatMap(sentence=>sentence.length<=190?[sentence.trim()]:(sentence.match(/.{1,180}(?:\s|$)/g)||[sentence]).map(part=>part.trim())).filter(Boolean)}
function voices(){return window.speechSynthesis?.getVoices?.()||[]}
function preferredVoice(){const list=voices(),male=/Alex|Daniel|Aaron|Arthur|Fred|Ralph|Tom|Oliver|James|Eddy|Reed|Rocko|Grandpa|David|Mark|Guy|Christopher|Eric|Roger|Steffan|Ryan|Andrew|Brian|Male/i;if(state.voiceName){const exact=list.find(voice=>voice.name===state.voiceName);if(exact)return exact}return list.find(voice=>/^en-US$/i.test(voice.lang)&&male.test(voice.name))||list.find(voice=>/^en/i.test(voice.lang)&&male.test(voice.name))||list.find(voice=>/^en-US$/i.test(voice.lang))||list.find(voice=>/^en/i.test(voice.lang))||null}
function populateVoices(){const select=$("#voiceSelect"),english=voices().filter(voice=>/^en/i.test(voice.lang));if(!english.length)return;select.innerHTML='<option value="">Best available English voice</option>'+english.map(voice=>`<option value="${esc(voice.name)}" ${voice.name===state.voiceName?"selected":""}>${esc(voice.name)} · ${esc(voice.lang)}</option>`).join("")}
function speak(text,title="Morpheus",onDone=null){if(!("speechSynthesis"in window)){toast("Voice playback isn’t available here");return}speechSynthesis.cancel();state.speech={chunks:splitSpeech(text),index:0,active:true,paused:false,onDone};$("#playerTitle").textContent=title;$("#playerPause").textContent="Ⅱ";$("#player").classList.remove("hidden");setPet("speaking");speakNext()}
function speakNext(){const speech=state.speech;if(!speech.active||speech.paused)return;if(speech.index>=speech.chunks.length){const done=speech.onDone;stopSpeech(false);if(done)done();return}const utterance=new SpeechSynthesisUtterance(speech.chunks[speech.index]);utterance.lang="en-US";utterance.rate=state.rate;utterance.pitch=.94;const voice=preferredVoice();if(voice)utterance.voice=voice;utterance.onend=()=>{if(!speech.active||speech.paused)return;speech.index+=1;progress();setTimeout(speakNext,35)};utterance.onerror=()=>{if(!speech.active)return;speech.index+=1;progress();setTimeout(speakNext,60)};speechSynthesis.speak(utterance);progress()}
function progress(){$("#progressBar").style.width=`${Math.min(100,state.speech.index/Math.max(1,state.speech.chunks.length)*100)}%`}
function stopSpeech(hide=true){if("speechSynthesis"in window)speechSynthesis.cancel();state.speech.active=false;state.speech.paused=false;state.speech.onDone=null;if(state.briefing)setPet(basePetMode());if(hide)$("#player").classList.add("hidden");else setTimeout(()=>$("#player").classList.add("hidden"),300)}
function setRate(rate){state.rate=Number(rate);localStorage.setItem("morpheus:rate",String(state.rate));$$(".speed").forEach(button=>button.classList.toggle("active",Number(button.dataset.rate)===state.rate));if(state.speech.active&&!state.speech.paused){speechSynthesis.cancel();setTimeout(speakNext,80)}}
function switchView(target){$$(".view").forEach(view=>view.classList.toggle("active",view.dataset.view===target));$$(".nav-button").forEach(button=>button.classList.toggle("active",button.dataset.target===target));window.scrollTo({top:0,behavior:"smooth"});if(target!=="talk"&&["listening","thinking"].includes(state.petMode))setPet(basePetMode())}
async function ask(raw){const command=raw.trim();if(!command)return;$("#askInput").value=command;$("#answerCard").classList.remove("hidden");$("#answerText").textContent="Thinking…";$("#answerFollow").textContent="";$("#answerFull").classList.add("hidden");setPet("thinking");$("#talkHeading").textContent="I’m on it.";try{const answer=await api("POST",{action:"ask",command,contextTopicId:state.contextTopicId,sessionId:getConversationId()});state.answer=answer;if(answer.topicId)state.contextTopicId=answer.topicId;$("#answerText").textContent=answer.shortAnswer;$("#answerFollow").textContent=answer.followUp||"";$("#answerFull").classList.toggle("hidden",!answer.fullAnswer);$("#talkHeading").textContent=answer.confirmationRequired?"Nothing sent yet.":"Here’s the short answer.";if(["acknowledged","deferred"].includes(answer.kind))await loadBriefing();speak(answer.shortAnswer,"Morpheus")}catch{$("#answerText").textContent="I couldn’t reach the briefing service just now.";$("#answerFollow").textContent="Try again in a moment.";$("#talkHeading").textContent="I’m still here.";setPet(basePetMode())}}
function getConversationId(){let id=sessionStorage.getItem("morpheus:conversation");if(!id){id=uuid();sessionStorage.setItem("morpheus:conversation",id)}return id}
function setupRecognition(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){$("#micLabel").textContent="Tap the text box and use iPhone dictation";return}const recognition=new Recognition();recognition.lang="en-US";recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onstart=()=>{$("#micButton").classList.add("listening");$("#micLabel").textContent="Listening…";$("#talkHeading").textContent="I’m listening.";setPet("listening")};recognition.onend=()=>{$("#micButton").classList.remove("listening");if(state.petMode==="listening")setPet(basePetMode())};recognition.onerror=()=>{$("#micLabel").textContent="Tap to try again";$("#talkHeading").textContent="What do you want to know?"};recognition.onresult=event=>{const text=event.results[0][0].transcript;$("#micLabel").textContent=text;ask(text)};state.recognition=recognition}
function startListening(){if(state.recognition){try{state.recognition.start()}catch{}}else{$("#askInput").focus();toast("Use the microphone on your iPhone keyboard")}}
function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("show"),2400)}
async function install(){if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$("#installButton").classList.add("hidden")}else $("#installModal").classList.remove("hidden")}
function setupPwa(){if("serviceWorker"in navigator&&!state.isTauri)navigator.serviceWorker.register("./sw.js").then(reg=>reg.update()).catch(console.warn);window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();state.deferredInstall=event;$("#installButton").classList.remove("hidden")});const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=matchMedia("(display-mode: standalone)").matches||navigator.standalone;if(isiOS&&!standalone)$("#installButton").classList.remove("hidden")}
async function enableNotifications(){if(!("Notification"in window)){toast("Notifications aren’t available here");return}const permission=await Notification.requestPermission();$("#notificationButton").textContent=permission==="granted"?"Notifications on ✓":"Notifications unavailable";toast(permission==="granted"?"Notifications are on":"Notifications were not enabled")}
async function expand(target="home"){if(state.isTauri){document.documentElement.classList.remove("compact-mode");await nativeInvoke("expand_companion")}switchView(target)}
function bind(){
$("#pairForm").addEventListener("submit",async event=>{event.preventDefault();const button=$("#pairButton"),code=$("#pairCode").value.trim();if(!code)return;button.disabled=true;button.innerHTML='<span class="spinner"></span> Pairing…';$("#pairError").textContent="";try{await pair(code);$("#pairCode").value=""}catch{$("#pairError").textContent="That code didn’t work. Check it and try again."}finally{button.disabled=false;button.textContent="Pair this device"}});
$$(".nav-button").forEach(button=>button.onclick=()=>switchView(button.dataset.target));$("#homeTalk").onclick=()=>switchView("talk");$("#homeBrief").onclick=()=>{switchView("briefing");speak(fullBriefingText(),"Your briefing")};$("#playBriefing").onclick=()=>speak(fullBriefingText(),"Your briefing",()=>Promise.all(updates().map(item=>setTopicState(item.id,"heard"))));
$("#askForm").addEventListener("submit",event=>{event.preventDefault();ask($("#askInput").value)});$$(".quick button").forEach(button=>button.onclick=()=>ask(button.textContent));$("#micButton").onclick=startListening;$("#answerListen").onclick=()=>state.answer&&speak(state.answer.shortAnswer,"Morpheus");$("#answerFull").onclick=()=>{if(!state.answer?.fullAnswer)return;$("#answerText").textContent=state.answer.fullAnswer;$("#answerFollow").textContent="";$("#answerFull").classList.add("hidden");speak(state.answer.fullAnswer,"Full explanation",()=>state.answer.topicId&&setTopicState(state.answer.topicId,"heard"))};
$("#settingsButton").onclick=()=>$("#settingsModal").classList.remove("hidden");$("#closeSettings").onclick=()=>$("#settingsModal").classList.add("hidden");$("#settingsModal").onclick=event=>{if(event.target.id==="settingsModal")event.currentTarget.classList.add("hidden")};$("#installButton").onclick=install;$("#settingsInstall").onclick=install;$("#closeInstall").onclick=()=>$("#installModal").classList.add("hidden");$("#notificationButton").onclick=enableNotifications;$("#unpairButton").onclick=()=>{if(!confirm("Unpair Morpheus from this device?"))return;localStorage.removeItem("morpheus:session");state.session="";$("#settingsModal").classList.add("hidden");showPair()};
$$(".speed").forEach(button=>button.onclick=()=>setRate(button.dataset.rate));$("#voiceSelect").onchange=event=>{state.voiceName=event.target.value;localStorage.setItem("morpheus:voice",state.voiceName);toast("Voice updated")};$("#playerPause").onclick=()=>{if(!state.speech.active)return;if(state.speech.paused){state.speech.paused=false;$("#playerPause").textContent="Ⅱ";setPet("speaking");speakNext()}else{state.speech.paused=true;speechSynthesis.cancel();$("#playerPause").textContent="▶";setPet(basePetMode())}};$("#playerStop").onclick=()=>stopSpeech();
$("#compactOpen").onclick=()=>expand("home");$("#compactTalk").onclick=()=>expand("talk");$("#compactBrief").onclick=()=>expand("briefing")}
async function boot(){bind();setRate(state.rate);setupRecognition();setupPwa();populateVoices();if("speechSynthesis"in window)speechSynthesis.onvoiceschanged=populateVoices;scheduleBlink();if(!state.session)await migrateLegacyPair();if(!state.session){showPair();return}try{await loadBriefing();showApp()}catch(error){if(error.status===401){localStorage.removeItem("morpheus:session");state.session="";showPair("Please pair this device again.")}else showPair("Morpheus couldn’t connect. Check your connection and try again.")}}
document.addEventListener("DOMContentLoaded",boot);
})();
