const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const API='https://zadxvmpgngwtpsmdkcod.supabase.co/functions/v1/morpheus-george-pwa';
const state={briefing:null,rate:1,screen:'home',briefTab:'updates',speech:{chunks:[],index:0,active:false,paused:false},token:localStorage.getItem('morpheus:pair')||'',deferredInstall:null,recognition:null};
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const heardSet=()=>new Set(JSON.parse(localStorage.getItem('morpheus:heard')||'[]'));
const isHeard=id=>heardSet().has(id);
function markHeard(id){const s=heardSet();s.add(id);localStorage.setItem('morpheus:heard',JSON.stringify([...s]));render()}
function greeting(){const h=new Date().getHours();return h<12?'GOOD MORNING, GEORGE':h<18?'GOOD AFTERNOON, GEORGE':'GOOD EVENING, GEORGE'}
function friendlyGreeting(){const h=new Date().getHours();return h<12?'Good morning.':h<18?'Good afternoon.':'Good evening.'}
async function fetchBriefing(token){const r=await fetch(API,{headers:{'x-pair-code':token},cache:'no-store'});if(!r.ok)throw new Error(r.status===401?'pair':'network');return r.json()}
async function pair(token){$('#pairError').textContent='Checking…';try{state.briefing=await fetchBriefing(token);state.token=token;localStorage.setItem('morpheus:pair',token);$('#pairScreen').classList.add('hidden');$('#app').classList.remove('hidden');$('#pairError').textContent='';render();switchScreen('home')}catch(e){$('#pairError').textContent=e.message==='pair'?'That pairing code is not valid.':'Could not reach Morpheus. Try again.'}}
function counts(){const u=state.briefing?.updates||[];return{updates:u.filter(x=>!isHeard(x.id)).length,all:u.length,needs:u.filter(x=>x.needsGeorge).length,next:state.briefing?.next?.length||0}}
function card(u){return `<article class="update-card ${u.needsGeorge?'attention':''}"><div class="update-top"><div><div class="project">${esc(u.project)}</div><h2>${esc(u.title)}</h2></div><span class="badge ${u.needsGeorge?'need':''}">${u.needsGeorge?'NEEDS YOU':isHeard(u.id)?'HEARD':'UPDATE'}</span></div><p class="summary">${esc(u.summary)}</p><ul class="bullets">${u.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>${u.action?`<div class="action-copy"><strong>What Saad needs</strong><p>${esc(u.action)}</p></div>`:''}<div class="card-actions"><button class="primary listen-update" data-id="${u.id}">▶ Listen</button><button class="ghost heard-update" data-id="${u.id}">${isHeard(u.id)?'Heard ✓':'I got it'}</button></div></article>`}
function bindCards(){$$('.listen-update').forEach(b=>b.onclick=()=>{const u=state.briefing.updates.find(x=>x.id===b.dataset.id);if(u){markHeard(u.id);speak(u.narration,u.project)}});$$('.heard-update').forEach(b=>b.onclick=()=>markHeard(b.dataset.id))}
function render(){if(!state.briefing)return;const c=counts();$('#greeting').textContent=greeting();$('#homeGreeting').textContent=friendlyGreeting();$('#homeUpdateCount').textContent=c.updates;$('#homeNeedsCount').textContent=c.needs;$('#heroUpdateCount').textContent=c.updates;$('#heroNeedsCount').textContent=c.needs;$('#heroNextCount').textContent=c.next;$('#heroTitle').textContent=c.needs?`${c.needs} thing${c.needs===1?'':'s'} need you.`:'Everything is moving.';$('#heroSubtitle').textContent=c.needs?`${c.updates} unread update${c.updates===1?' is':'s are'} ready. I can explain the important part.`:`${c.updates} unread update${c.updates===1?' is':'s are'} ready. Nothing urgent is waiting.`;
  if(c.needs){$('#homeMessage').textContent=`A few things moved. ${c.needs} ${c.needs===1?'thing needs':'things need'} you when you're ready.`;$('#petStatus').textContent=`${c.needs} ${c.needs===1?'thing needs':'things need'} you.`;$('#petStage').classList.add('state-attention');$('#navNeedsBadge').textContent=c.needs;$('#navNeedsBadge').classList.remove('hidden')}else{$('#homeMessage').textContent=c.updates?'There are a few new things to know. Nothing needs a decision right now.':'Everything is moving. Ask me whenever you want the picture.';$('#petStatus').textContent='All moving normally.';$('#petStage').classList.remove('state-attention');$('#navNeedsBadge').classList.add('hidden')}
  $('#briefTime').textContent=c.all<=3?'About 1 minute':c.all<=6?'About 3 minutes':'A few minutes';const d=new Date(state.briefing.meta.updatedAt);$('#lastUpdated').textContent=`Updated ${d.toLocaleDateString(undefined,{month:'short',day:'numeric'})} · ${d.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}`;
  $('#updatesView').innerHTML=state.briefing.updates.map(card).join('');$('#needsView').innerHTML=state.briefing.updates.filter(x=>x.needsGeorge).map(card).join('')||'<div class="empty-card"><h2>Nothing needs you.</h2><p class="summary">Morpheus will surface it here when a decision is actually required.</p></div>';$('#nextView').innerHTML=state.briefing.next.map(n=>`<article class="next-card"><div class="date">${esc(n.date)}</div><h2>${esc(n.title)}</h2><p class="summary">${esc(n.detail)}</p></article>`).join('');renderHistory();bindCards();}
function renderHistory(){const heard=heardSet(),b=state.briefing;if(!b)return;const chips=b.updates.map(u=>`<span class="history-chip ${heard.has(u.id)?'heard':''}">${esc(u.project)}${heard.has(u.id)?' · heard':''}</span>`).join('');$('#historyList').innerHTML=`<article class="history-day"><div class="history-date">Today</div><h2>Current briefing</h2><div class="history-projects">${chips}</div><p class="history-note">${heard.size} of ${b.updates.length} topics marked heard on this device.</p></article>`}
function switchScreen(name){state.screen=name;['home','briefing','talk','history'].forEach(n=>$(`#${n}View`).classList.toggle('hidden',n!==name));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));window.scrollTo({top:0,behavior:'smooth'})}
function switchBriefTab(tab){state.briefTab=tab;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));['updates','needs','next'].forEach(n=>$(`#${n}View`).classList.toggle('hidden',n!==tab))}
function split(t){return(t.replace(/\s+/g,' ').match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[t]).flatMap(s=>s.length<=185?[s.trim()]:(s.match(/.{1,175}(?:\s|$)/g)||[s]).map(x=>x.trim())).filter(Boolean)}
function voice(){const v=speechSynthesis.getVoices(),m=/Alex|Daniel|Aaron|Arthur|Fred|Ralph|Tom|Oliver|James|Eddy|Reed|Rocko|Grandpa|David|Mark|Guy|Christopher|Eric|Roger|Steffan|Ryan|Andrew|Brian|Male/i;return v.find(x=>/^en-US$/i.test(x.lang)&&m.test(x.name))||v.find(x=>/^en/i.test(x.lang)&&m.test(x.name))||v.find(x=>/^en-US$/i.test(x.lang))||v.find(x=>/^en/i.test(x.lang))||null}
function setPetMode(mode){$('#petStage').classList.remove('state-listening','state-speaking','state-thinking');$('#talkPet').classList.remove('state-listening','state-speaking','state-thinking');if(mode){$('#petStage').classList.add(`state-${mode}`);$('#talkPet').classList.add(`state-${mode}`)}const labels={listening:'Listening…',speaking:'Talking to you',thinking:'Thinking…'};$('#petStateText').textContent=labels[mode]||'Morpheus is awake';$('#talkState').textContent=labels[mode]||"I'm listening when you're ready."}
function speak(text,title='Morpheus'){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();state.speech={chunks:split(text),index:0,active:true,paused:false};$('#playerTitle').textContent=title;$('#playerPause').textContent='Pause';$('#player').classList.remove('hidden');setPetMode('speaking');nextSpeech()}
function nextSpeech(){if(!state.speech.active||state.speech.paused)return;if(state.speech.index>=state.speech.chunks.length){stopSpeech(false);return}const u=new SpeechSynthesisUtterance(state.speech.chunks[state.speech.index]);u.lang='en-US';u.rate=state.rate;u.pitch=.95;const v=voice();if(v)u.voice=v;u.onend=()=>{if(state.speech.active&&!state.speech.paused){state.speech.index++;progress();setTimeout(nextSpeech,35)}};u.onerror=()=>{state.speech.index++;progress();setTimeout(nextSpeech,70)};speechSynthesis.speak(u);progress()}
function progress(){const n=state.speech.chunks.length||1;$('#progressBar').style.width=`${Math.min(100,state.speech.index/n*100)}%`}
function stopSpeech(h=true){speechSynthesis?.cancel();state.speech.active=false;state.speech.paused=false;setPetMode(null);if(h)$('#player').classList.add('hidden');else setTimeout(()=>$('#player').classList.add('hidden'),350)}
function briefingText(){const b=state.briefing,needs=b.updates.filter(x=>x.needsGeorge);return`${b.meta.fullBriefingLead} ${b.updates.length} areas have moved. ${needs.length} need a decision or input from you. ${b.updates.map(u=>`${u.project}. ${u.narration}`).join(' ')} ${needs.length?'The things I need from you are: '+needs.map(u=>u.action).join(' And '):'Nothing needs a decision from you right now.'}`}
function answer(q0){const q=q0.trim().toLowerCase(),u=state.briefing.updates;if(!q)return'Ask me anything about what is moving.';if(/need|decision|what.*me|saad.*need/.test(q)){const n=u.filter(x=>x.needsGeorge);return n.length?`There ${n.length===1?'is':'are'} ${n.length} item${n.length===1?'':'s'} that need you. ${n.map(x=>`${x.project}: ${x.action}`).join(' ')}`:'Nothing needs you right now.'}if(/change|today|update|what.*happen/.test(q)&&!/puck|outlaw|sho|leviathan|account|sale/.test(q))return`There are ${u.length} active areas in this briefing. ${u.map(x=>`${x.project}: ${x.summary}`).join(' ')}`;for(const[re,id]of[[/outlaw|plastic|cup|gun smoke/,'outlaw'],[/puck|apex|rubber/,'pucks'],[/sho|koi|frank/,'shokoi'],[/leviathan|dog|cat|freeze/,'leviathan'],[/sale|ecosystem|aquanix|wave/,'sales'],[/account|invoice|money|ari/,'accounts']])if(re.test(q)){const x=u.find(y=>y.id===id);if(x)return`${x.summary} ${x.narration}`}return'I do not have a confident answer for that in this briefing yet. I would rather not guess.'}
function submitAsk(t){if(!t.trim())return;setPetMode('thinking');$('#answerCard').classList.add('hidden');setTimeout(()=>{const a=answer(t);$('#answerText').textContent=a;$('#answerCard').dataset.answer=a;$('#answerCard').classList.remove('hidden');setPetMode(null)},420)}
function speechRecognition(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){$('#micLabel').textContent='Type or use dictation';$('#voiceFallback').classList.remove('hidden');$('#micButton').onclick=()=>$('#askInput').focus();return}const r=new R();r.lang='en-US';r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>{$('#micButton').classList.add('listening');$('#micLabel').textContent='Listening…';setPetMode('listening')};r.onend=()=>{$('#micButton').classList.remove('listening');$('#micLabel').textContent='Tap to talk';if(!state.speech.active)setPetMode(null)};r.onerror=()=>{$('#micButton').classList.remove('listening');$('#micLabel').textContent='Tap to try again';setPetMode(null)};r.onresult=e=>{const t=e.results[0][0].transcript;$('#askInput').value=t;submitAsk(t)};state.recognition=r;$('#micButton').onclick=()=>{try{r.start()}catch{}}}
function startTalk(){switchScreen('talk');setTimeout(()=>{if(state.recognition){try{state.recognition.start()}catch{}}else $('#askInput').focus()},250)}
function setupInstall(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;$('#installPwa').classList.remove('hidden')});const ios=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone;if(ios&&!standalone)$('#installPwa').classList.remove('hidden');$('#installPwa').onclick=async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$('#installPwa').classList.add('hidden')}else $('#installHelp').classList.remove('hidden')}}
function bind(){$('#pairButton').onclick=()=>pair($('#pairCode').value.trim().toUpperCase());$('#pairCode').addEventListener('keydown',e=>{if(e.key==='Enter')pair(e.target.value.trim().toUpperCase())});$('#homeBrand').onclick=()=>switchScreen('home');$$('.nav-item').forEach(b=>b.onclick=()=>switchScreen(b.dataset.screen));$('#openBriefing').onclick=()=>switchScreen('briefing');$('#talkFromHome').onclick=startTalk;$('#briefFromHome').onclick=()=>speak(briefingText(),'Full update');$('#playBriefing').onclick=()=>speak(briefingText(),'Full update');$$('.tab,.stat').forEach(b=>b.onclick=()=>{switchScreen('briefing');switchBriefTab(b.dataset.tab)});$('#playerPause').onclick=()=>{if(!state.speech.active)return;if(state.speech.paused){state.speech.paused=false;$('#playerPause').textContent='Pause';setPetMode('speaking');nextSpeech()}else{state.speech.paused=true;speechSynthesis.cancel();$('#playerPause').textContent='Resume';setPetMode(null)}};$('#playerStop').onclick=()=>stopSpeech();$$('.speed').forEach(b=>b.onclick=()=>{state.rate=Number(b.dataset.rate);$$('.speed').forEach(x=>x.classList.toggle('active',x===b));if(state.speech.active&&!state.speech.paused){speechSynthesis.cancel();setTimeout(nextSpeech,80)}});$('#askSend').onclick=()=>submitAsk($('#askInput').value);$('#askInput').onkeydown=e=>{if(e.key==='Enter')submitAsk(e.target.value)};$$('.quick-asks button').forEach(b=>b.onclick=()=>{$('#askInput').value=b.textContent;submitAsk(b.textContent)});$('#playAnswer').onclick=()=>{const a=$('#answerCard').dataset.answer;if(a)speak(a,'Morpheus')};$('#notificationsButton').onclick=async()=>{if(!('Notification'in window))return;const p=await Notification.requestPermission();$('#notificationsButton').textContent=p==='granted'?'Notifications on ✓':'Notifications'};$('#closeInstallHelp').onclick=()=>$('#installHelp').classList.add('hidden');$('#unpairButton').onclick=()=>{localStorage.removeItem('morpheus:pair');location.reload()}}
document.addEventListener('DOMContentLoaded',async()=>{bind();speechRecognition();setupInstall();if(state.token)await pair(state.token);else $('#pairScreen').classList.remove('hidden')});