'use client';
import React,{FormEvent,useEffect,useState} from 'react';
import Link from '@/app/components/link';
import {ArrowRight,Check,ChevronRight,Clock3,Copy,Gift,KeyRound,LockKeyhole,LogOut,PackageOpen,RefreshCw,Repeat2,ScanLine,ShieldCheck,Sparkles,Trophy,UserRound,Users,X} from 'lucide-react';
import {adminDemo,collectorDemo,initialQuestState,QUEST_SESSION,QUEST_STORAGE,QuestCollectible,QuestState,questThemes,themeById} from '@/lib/puckquest';
import {QuestPuck as MiniPuck} from './quest-puck';

type Session={email:string;role:'collector'|'admin'};
type Tab='collection'|'redeem'|'swaps'|'rewards'|'history';
const DAY=86_400_000;

function useQuest(){
 const [state,setState]=useState<QuestState>(initialQuestState());
 const [ready,setReady]=useState(false);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{const value=JSON.parse(localStorage.getItem(QUEST_STORAGE)||'null');if(value?.version===3)setState(value)}catch{}setReady(true)});return()=>{active=false}},[]);
 useEffect(()=>{if(ready)localStorage.setItem(QUEST_STORAGE,JSON.stringify(state))},[ready,state]);
 const update=(recipe:(draft:QuestState)=>void)=>setState(current=>{const next=structuredClone(current);recipe(next);return next});
 const reset=()=>{const next=initialQuestState();setState(next);localStorage.setItem(QUEST_STORAGE,JSON.stringify(next))};
 return {state,update,reset,ready};
}

function useSession(expected?:Session['role']){
 const [session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{const value=JSON.parse(localStorage.getItem(QUEST_SESSION)||'null');if(value?.email&&value?.role&&(!expected||value.role===expected))setSession(value)}catch{}setReady(true)});return()=>{active=false}},[expected]);
 return {session,ready,signOut:()=>{localStorage.removeItem(QUEST_SESSION);location.assign('/puckquest')}};
}

function DemoBadge(){return <div className="pq-demo-badge"><span>LIVE DEMO</span><p>No customer data. Changes stay in this browser.</p></div>}

export function QuestExperience(){
 const art=questThemes.slice(0,16);
 return <main id="main" className="pq-site">
  <section className="pq-hero">
   <div className="pq-hero-grid" aria-hidden="true"/><div className="pq-hero-copy"><p className="pq-kicker">APEX PUCKQUEST / EDITION 01</p><h1>CLAIM THE<br/><em>ICE.</em></h1><p className="pq-lede">The mini puck collection with a permanent digital record. Open the packet. Enter the hidden code. Reveal your theme. Own it until you trade or transfer it.</p><div className="pq-actions"><Link className="pq-primary" href="/puckquest/login">Enter the Quest <ArrowRight/></Link><Link className="pq-secondary" href="/products/apex-puckquest-e1">Buy Edition 01 <ChevronRight/></Link></div><Link className="pq-admin-preview" href="/puckquest/admin/login">Apex admin preview <ChevronRight/></Link><div className="pq-proof"><span><b>32</b> THEMES</span><span><b>01</b> CODE / PUCK</span><span><b>∞</b> OWNERSHIP HISTORY</span></div></div>
   <div className="pq-hero-object" aria-label="Mini keychain puck collectible"><img className="pq-keytag" src="/assets/puckquest/mini-keytag-pack.webp" alt="Apex mini keytag puck on retail card" width="700" height="1200"/><MiniPuck themeId="boston" className="pq-hero-puck pq-puck-one" keytag eager/><MiniPuck themeId="kraken" className="pq-hero-puck pq-puck-two" keytag eager/><MiniPuck themeId="colorado" className="pq-hero-puck pq-puck-three" keytag eager/><span className="pq-orbit">SERIES E1 · UNIQUE CLAIM · TRANSFERABLE OWNERSHIP</span></div>
  </section>
  <section className="pq-marquee" aria-label="PuckQuest principles"><span>OPEN</span><i/> <span>REVEAL</span><i/> <span>REGISTER</span><i/> <span>COLLECT</span><i/> <span>SWAP</span><i/> <span>COMPLETE</span></section>
  <section className="pq-section pq-origin"><div><p className="pq-kicker">THE OBJECT</p><h2>SMALL PUCK.<br/>REAL CLAIM.</h2><p>PuckQuest uses the mini keychain-style puck—not a regulation game puck. The artwork is printed on the physical piece. The sealed packet carries the one-time series code that registers its digital ownership.</p><div className="pq-rule"><ShieldCheck/><span><b>The code can be redeemed once.</b><small>The collectible can change hands; its original code can never be reused.</small></span></div></div><figure className="pq-origin-product"><div className="pq-origin-visual"><span className="pq-origin-series">PUCKQUEST / EDITION 01</span><img className="pq-origin-pack" src="/assets/puckquest/mini-keytag-pack.webp" alt="Apex mini keytag puck retail packaging" width="700" height="1200" loading="lazy"/><MiniPuck themeId="boston" className="pq-origin-puck" keytag/><span className="pq-origin-spec">MINI KEYTAG<br/>PRINTED COLLECTIBLE</span></div><figcaption>APEX PUCKQUEST MINI KEYTAG / EDITION 01</figcaption></figure></section>
  <section className="pq-section pq-how"><header><p className="pq-kicker">THE LOOP</p><h2>FROM PACKET<br/>TO PROVENANCE.</h2></header><div className="pq-steps">{[
   ['01','BUY','Choose a League, Conference or Division mystery pack.'],['02','REVEAL','Open it and discover the printed theme.'],['03','CLAIM','Enter the hidden E1 code in your collector account.'],['04','KEEP OR MOVE','Hold it, list a duplicate, swap it or transfer it after a sale.']
  ].map(([number,title,copy])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="pq-gallery"><div className="pq-gallery-copy"><p className="pq-kicker">32 / EDITION 01</p><h2>EVERY PACK<br/>CHANGES THE BOARD.</h2><p>Owned designs burn bright. Missing designs stay in shadow. Duplicates become trade power.</p><Link className="pq-secondary" href="/puckquest/login">Open collector demo <ChevronRight/></Link></div><div className="pq-art-wall">{art.map((theme,index)=><div key={theme.id} style={{'--i':index} as React.CSSProperties}><img src={theme.image} alt={`${theme.name} collection artwork`} width="360" height="360" loading="lazy"/><span>{theme.short}</span></div>)}</div></section>
  <section className="pq-section pq-ledger"><div className="pq-ledger-card"><div className="pq-scan"><ScanLine/><span>E1-00042</span></div><h3>ONE PUCK.<br/>ONE LIVING RECORD.</h3><ol><li><span>01</span><b>REGISTERED</b><small>Code consumed. First owner recorded.</small></li><li><span>02</span><b>LISTED</b><small>Duplicate offered to the collector network.</small></li><li><span>03</span><b>TRANSFERRED</b><small>New owner accepted. Full history preserved.</small></li></ol></div><div className="pq-ledger-copy"><p className="pq-kicker">OWNERSHIP, NOT SCREENSHOTS</p><h2>THE CODE<br/>DOESN’T RESET.</h2><p>Once claimed, a packet code is finished forever. Swaps and sales move the registered puck itself to the next collector. That keeps the series scarce, understandable and auditable.</p><div className="pq-actions"><Link className="pq-primary" href="/puckquest/login">Try the claim flow <ArrowRight/></Link><Link className="pq-secondary" href="/puckquest/admin/login">Inspect admin <ChevronRight/></Link></div></div></section>
  <section className="pq-reward-banner"><div><p className="pq-kicker">THE OFFICIAL PRIZE RUN</p><h2>THE BOARD<br/>PAYS BACK.</h2><p>Build a division, a conference or the full 32-team set. Same-edition sets unlock the largest tiers, while duplicates and future editions create their own paths.</p><div className="pq-speed-copy"><Clock3/><span><b>THE SPEED CLOCK STARTS WITH YOUR FIRST PUCK.</b><small>Complete one same-edition set inside 30, 60 or 90 calendar days for a $1,000, $500 or $250 bonus.</small></span></div></div><div className="pq-reward-track">{[['$300','DIVISION'],['$750','CONFERENCE'],['$1.5K','ALL 32'],['$2K','E1 CONFERENCE'],['$5K','E1 FULL SET']].map(([amount,label])=><span key={label}><b>{amount}</b><small>{label}</small></span>)}</div></section>
 </main>
}

export function QuestLogin({admin=false}:{admin?:boolean}){
 const demo=admin?adminDemo:collectorDemo;
 const [email,setEmail]=useState(demo.email),[password,setPassword]=useState(demo.password),[error,setError]=useState('');
 function submit(event:FormEvent){event.preventDefault();if(email.trim().toLowerCase()!==demo.email||password!==demo.password){setError('Use the demo access shown below. This preview has no live customer accounts.');return}localStorage.setItem(QUEST_SESSION,JSON.stringify({email:demo.email,role:admin?'admin':'collector'}));location.assign(admin?'/puckquest/admin':'/puckquest/collector')}
 return <main id="main" className="pq-auth"><section className="pq-auth-art"><Link href="/puckquest" className="pq-back">← PUCKQUEST E1</Link><MiniPuck themeId={admin?'blackhawks':'boston'} className="pq-login-puck" eager/><p>{admin?'CONTROL THE SERIES':'YOUR QUEST STARTS HERE'}</p></section><section className="pq-auth-panel"><DemoBadge/><p className="pq-kicker">{admin?'APEX OPERATIONS':'COLLECTOR ACCESS'}</p><h1>{admin?'ADMIN LOGIN':'ENTER THE LOCKER'}</h1><p>{admin?'Review codes, collectors, designs, rewards and the ownership ledger.':'Claim codes, view your collection, trade duplicates and track every milestone.'}</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<p role="alert" className="pq-error">{error}</p>}<button className="pq-primary" type="submit">{admin?'Open admin console':'Open my collection'} <ArrowRight/></button></form><div className="pq-demo-access"><span>DEMO ACCESS</span><button onClick={()=>{setEmail(demo.email);setPassword(demo.password)}}><b>{demo.email}</b><small>{demo.password}</small><Copy/></button></div><Link className="pq-switch" href={admin?'/puckquest/login':'/puckquest/admin/login'}>{admin?'Collector login':'Apex admin login'} <ChevronRight/></Link></section></main>
}

function LockedDashboard({admin=false}:{admin?:boolean}){return <main id="main" className="pq-locked"><LockKeyhole/><p className="pq-kicker">SESSION REQUIRED</p><h1>{admin?'ADMIN CONSOLE LOCKED':'COLLECTOR LOCKER LOCKED'}</h1><p>Use the dedicated demo login to inspect this PuckQuest experience.</p><Link className="pq-primary" href={admin?'/puckquest/admin/login':'/puckquest/login'}>Go to login <ArrowRight/></Link></main>}

function DashboardShell({children,session,signOut,admin=false}:{children:React.ReactNode;session:Session;signOut:()=>void;admin?:boolean}){
 return <main id="main" className="pq-app"><header className="pq-appbar"><div><span className="pq-app-mark">PQ</span><div><b>{admin?'APEX CONTROL':'COLLECTOR LOCKER'}</b><small>EDITION 01 / DEMO LEDGER</small></div></div><div><span className="pq-identity"><UserRound/><small>{session.email}</small></span><button onClick={signOut}>Sign out <LogOut/></button></div></header>{children}</main>
}

export function CollectorDashboard(){
 const {session,ready:sessionReady,signOut}=useSession('collector');
 const {state,update,ready}=useQuest();
 const [tab,setTab]=useState<Tab>('collection'),[filter,setFilter]=useState<'all'|'owned'|'missing'>('all');
 const [code,setCode]=useState('PQ-E1-KRAK-9V4Q'),[message,setMessage]=useState(''),[revealed,setRevealed]=useState<string|null>(null);
 const [transferId,setTransferId]=useState(''),[recipient,setRecipient]=useState(''),[confirmTransfer,setConfirmTransfer]=useState(false);
 const [now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),60_000);return()=>window.clearInterval(timer)},[]);
 if(!sessionReady||!ready)return <main id="main" className="pq-loading"><span/></main>;
 if(!session)return <LockedDashboard/>;
 const sessionEmail=session.email;
 const mine=state.collectibles.filter(item=>item.ownerEmail===sessionEmail);
 const counts=new Map<string,number>();mine.forEach(item=>counts.set(item.themeId,(counts.get(item.themeId)||0)+1));
 const unique=counts.size,duplicates=mine.length-unique;
 const visible=questThemes.filter(theme=>filter==='all'||(filter==='owned'?counts.has(theme.id):!counts.has(theme.id)));
 const divisions=['Atlantic','Metropolitan','Central','Pacific'] as const,conferences=['Eastern','Western'] as const;
 const maxDivision=Math.max(...divisions.map(division=>questThemes.filter(theme=>theme.division===division&&counts.has(theme.id)).length));
 const maxConference=Math.max(...conferences.map(conference=>questThemes.filter(theme=>theme.conference===conference&&counts.has(theme.id)).length));
 const maxCopies=Math.max(0,...counts.values());
 const firstClaim=mine.map(item=>new Date(item.registeredAt).getTime()).filter(Number.isFinite).sort((a,b)=>a-b)[0]||now;
 const elapsed=Math.max(0,now-firstClaim);
 const speedWindow=elapsed<=30*DAY?30:elapsed<=60*DAY?60:elapsed<=90*DAY?90:null;
 const speedRemaining=speedWindow?Math.max(0,firstClaim+speedWindow*DAY-now):0;
 const speedClock=speedWindow?`${Math.floor(speedRemaining/DAY)}D ${String(Math.floor(speedRemaining%DAY/3_600_000)).padStart(2,'0')}H ${String(Math.floor(speedRemaining%3_600_000/60_000)).padStart(2,'0')}M`:'WINDOW CLOSED';
 const rewardProgress=(id:string)=>id==='division'?maxDivision:id==='booster'?maxCopies:id==='conference-same'||id==='conference-any'?maxConference:id==='legacy'?(mine.length?1:0):unique;
 const officialRewards=state.rewards.filter(reward=>reward.enabled);
 const nextReward=officialRewards.filter(reward=>!reward.id.startsWith('speed-')&&reward.id!=='legacy').map(reward=>({...reward,progress:rewardProgress(reward.id)})).filter(reward=>reward.progress<reward.threshold).sort((a,b)=>(a.threshold-a.progress)-(b.threshold-b.progress))[0];
 const duplicateItems=mine.filter(item=>(counts.get(item.themeId)||0)>1);
 const market=state.collectibles.filter(item=>item.status==='listed'&&item.ownerEmail!==sessionEmail);
 function redeem(){
  const value=code.trim().toUpperCase();const found=state.codes.find(item=>item.code===value);
  if(!found){setMessage('Code not found. Check every letter and number inside the packet.');return}
  if(found.status==='redeemed'){setMessage(found.redeemedBy===sessionEmail?'Already yours. This code was claimed to your locker.':'Code already claimed. Ownership can only move through a transfer.');return}
  if(found.status!=='ready'){setMessage('This code is not active. Contact Apex support with the packet.');return}
  const id=`claim-${Date.now()}`;const serial=`E1-${String(500+state.collectibles.length).padStart(5,'0')}`;const at=new Date().toISOString();
  update(draft=>{const target=draft.codes.find(item=>item.code===value)!;target.status='redeemed';target.redeemedAt=at;target.redeemedBy=sessionEmail;target.collectibleId=id;draft.collectibles.push({id,themeId:target.themeId,serial,ownerEmail:sessionEmail,registeredAt:at,status:'owned',history:[{at,event:'registered',to:sessionEmail,note:'Claimed from sealed packet code'}]});draft.audit.unshift({at,event:'code_redeemed',detail:`${value} claimed by ${sessionEmail}`})});
  setRevealed(found.themeId);setMessage('');
 }
 function toggleListing(item:QuestCollectible){const at=new Date().toISOString();update(draft=>{const target=draft.collectibles.find(row=>row.id===item.id)!;target.status=target.status==='listed'?'owned':'listed';target.history.push({at,event:target.status==='listed'?'listed':'unlisted',from:sessionEmail,note:target.status==='listed'?'Offered to the collector network':'Removed from the collector network'});draft.audit.unshift({at,event:'listing_changed',detail:`${target.serial} is now ${target.status}`})})}
 function swap(item:QuestCollectible){const offered=duplicateItems[0];if(!offered){setMessage('You need a duplicate before you can make this swap.');return}const at=new Date().toISOString(),other=item.ownerEmail;update(draft=>{const incoming=draft.collectibles.find(row=>row.id===item.id)!,outgoing=draft.collectibles.find(row=>row.id===offered.id)!;incoming.ownerEmail=sessionEmail;incoming.status='owned';incoming.history.push({at,event:'trade',from:other,to:sessionEmail,note:`Swapped for ${themeById(outgoing.themeId).name} ${outgoing.serial}`});outgoing.ownerEmail=other;outgoing.status='owned';outgoing.history.push({at,event:'trade',from:sessionEmail,to:other,note:`Swapped for ${themeById(incoming.themeId).name} ${incoming.serial}`});draft.audit.unshift({at,event:'trade_completed',detail:`${incoming.serial} exchanged for ${outgoing.serial}`})});setMessage(`Swap complete. ${themeById(item.themeId).name} is now in your locker.`)}
 function transfer(){if(!transferId||!recipient.trim()||!confirmTransfer)return;const at=new Date().toISOString(),email=recipient.trim().toLowerCase();update(draft=>{const item=draft.collectibles.find(row=>row.id===transferId&&row.ownerEmail===sessionEmail);if(!item)return;item.ownerEmail=email;item.status='owned';item.history.push({at,event:'transfer',from:sessionEmail,to:email,note:'Ownership transferred by collector'});if(!draft.users.some(user=>user.email===email))draft.users.push({email,name:email.split('@')[0],role:'collector'});draft.audit.unshift({at,event:'ownership_transferred',detail:`${item.serial} transferred from ${sessionEmail} to ${email}`})});setTransferId('');setRecipient('');setConfirmTransfer(false);setMessage('Transfer complete. The puck has left your locker and its history stays intact.')}
 return <DashboardShell session={session} signOut={signOut}><section className="pq-dashboard-head"><div><p className="pq-kicker">WELCOME BACK / ALEX</p><h1>{unique}<span>/32</span></h1><p>Unique Edition 01 themes registered.</p></div><div className="pq-dashboard-side"><div className="pq-speed-clock"><Clock3/><span><small>{speedWindow?`SPEED TIER ${speedWindow}-DAY WINDOW`:'SPEED TIER'}</small><b>{speedClock}</b><i>Started {new Date(firstClaim).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</i></span></div><div className="pq-next-reward"><Gift/><span><small>NEXT OFFICIAL TIER</small><b>{nextReward?`${nextReward.threshold-nextReward.progress} TO ${nextReward.name.toUpperCase()} · ${nextReward.prize}`:'ALL STANDARD TIERS COMPLETE'}</b><i><span style={{width:`${nextReward?Math.min(100,nextReward.progress/nextReward.threshold*100):100}%`}}/></i></span></div></div></section><nav className="pq-tabs" aria-label="Collector sections">{([['collection','Collection'],['redeem','Claim code'],['swaps','Swap & transfer'],['rewards','Rewards'],['history','History']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMessage('')}}>{label}{id==='redeem'&&<i/>}</button>)}</nav>{message&&<div className="pq-notice" role="status">{message}<button aria-label="Dismiss" onClick={()=>setMessage('')}><X/></button></div>}
 {tab==='collection'&&<section className="pq-panel"><header className="pq-panel-head"><div><p className="pq-kicker">MY EDITION 01</p><h2>THE BOARD.</h2></div><div className="pq-stats"><span><b>{mine.length}</b>TOTAL</span><span><b>{duplicates}</b>DUPLICATES</span><span><b>{32-unique}</b>MISSING</span></div></header><div className="pq-filters">{(['all','owned','missing'] as const).map(value=><button className={filter===value?'active':''} key={value} onClick={()=>setFilter(value)}>{value}</button>)}</div><div className="pq-collection-grid">{visible.map(theme=>{const count=counts.get(theme.id)||0;return <article key={theme.id} className={count?'owned':'missing'}><MiniPuck themeId={theme.id}/><div><span>{theme.short}</span><h3>{theme.name}</h3><small>{count?`${count} REGISTERED${count>1?' · DUPLICATE':''}`:'MISSING'}</small></div>{count>0&&<Check className="pq-owned-check"/>}</article>})}</div></section>}
 {tab==='redeem'&&<section className="pq-panel pq-redeem"><div className="pq-redeem-copy"><p className="pq-kicker">SEALED PACKET / ONE-TIME CLAIM</p><h2>ENTER THE<br/>HIDDEN CODE.</h2><p>The design is already printed on your mini puck. The packet code binds that physical piece to your collector account and creates its permanent serial history.</p><ol><li><span>01</span>Open the packet</li><li><span>02</span>Find the E1 code inside</li><li><span>03</span>Enter it exactly once</li></ol></div><div className="pq-code-console"><ScanLine/><label>PUCKQUEST CODE<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} spellCheck="false" autoCapitalize="characters"/></label><button className="pq-primary" onClick={redeem}>Verify and claim <ArrowRight/></button><p>Demo codes: <button onClick={()=>setCode('PQ-E1-BEAR-7K2M')}>BEAR-7K2M</button> · <button onClick={()=>setCode('PQ-E1-ICE9-2X7N')}>ICE9-2X7N</button></p></div></section>}
 {tab==='swaps'&&<section className="pq-panel"><header className="pq-panel-head"><div><p className="pq-kicker">DUPLICATES BECOME LEVERAGE</p><h2>MOVE THE PUCK.</h2></div><p>Swap registered collectibles inside the ledger, or transfer one after an outside sale. Payment is not handled by PuckQuest.</p></header><div className="pq-swap-grid"><div><h3>SWAP BOARD</h3><p>{duplicateItems.length?`Your ${themeById(duplicateItems[0].themeId).name} duplicate is ready to trade.`:'Collect a duplicate to unlock swaps.'}</p>{market.map(item=><article className="pq-market-row" key={item.id}><MiniPuck themeId={item.themeId}/><span><b>{themeById(item.themeId).name}</b><small>{item.serial} · WANTS BOSTON</small></span><button onClick={()=>swap(item)} disabled={!duplicateItems.length}>Swap <Repeat2/></button></article>)}</div><div className="pq-transfer"><h3>TRANSFER OWNERSHIP</h3><p>Use this only when the physical puck is changing hands. A transfer is final in the demo ledger.</p><label>YOUR REGISTERED PUCK<select value={transferId} onChange={e=>setTransferId(e.target.value)}><option value="">Select a puck</option>{mine.map(item=><option value={item.id} key={item.id}>{themeById(item.themeId).name} · {item.serial}</option>)}</select></label><label>NEW OWNER EMAIL<input type="email" value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="newowner@example.com"/></label><label className="pq-confirm"><input type="checkbox" checked={confirmTransfer} onChange={e=>setConfirmTransfer(e.target.checked)}/><span>I have handed over the physical mini puck and understand this removes it from my locker.</span></label><button className="pq-primary" disabled={!transferId||!recipient||!confirmTransfer} onClick={transfer}>Confirm transfer <ArrowRight/></button></div></div><div className="pq-my-pucks"><h3>MY TRADE LOCKER</h3>{mine.map(item=><button key={item.id} onClick={()=>toggleListing(item)}><span>{themeById(item.themeId).short}</span><b>{themeById(item.themeId).name}</b><small>{item.serial}</small><i>{item.status==='listed'?'LISTED — REMOVE':'MARK AVAILABLE'}</i></button>)}</div></section>}
 {tab==='rewards'&&<section className="pq-panel"><header className="pq-panel-head"><div><p className="pq-kicker">OFFICIAL CONTEST TRACK</p><h2>EVERY ROUTE<br/>TO THE PRIZE.</h2></div><p>Progress follows the rules George supplied: edition-specific sets cannot mix editions, while the any-edition tiers can. More than one collector may complete the same tier.</p></header><div className="pq-speed-panel"><div><Clock3/><span><small>EDITION 01 CLOCK</small><strong>{speedClock}</strong></span></div><p>Your clock began when your first Edition 01 puck was registered. Finish all 32 Edition 01 teams inside the active 30, 60 or 90-day window to qualify for its speed bonus.</p></div><div className="pq-rewards">{officialRewards.map(reward=>{const progress=rewardProgress(reward.id),windowDays=reward.id.startsWith('speed-')?Number(reward.id.split('-')[1]):null,done=reward.id==='legacy'?false:progress>=reward.threshold&&(!windowDays||elapsed<=windowDays*DAY);return <article className={done?'done':''} key={reward.id}><span>{done?<Trophy/>:<LockKeyhole/>}</span><small>{reward.goal}</small><h3>{reward.prize}</h3><b>{reward.name}</b><p>{reward.description}</p><em>{reward.id==='legacy'?'E1 REGISTERED':`${Math.min(progress,reward.threshold)} / ${reward.threshold}`}</em></article>})}</div><div className="pq-reward-note"><Gift/><span><b>PRIZE CLAIM CHECKLIST</b><p>A public Apex-tagged reveal post is required before a claim. Proof of purchase and a selfie with the pucks are required. One claim per household per tier; each puck may support only one prize claim.</p></span></div></section>}
 {tab==='history'&&<section className="pq-panel"><header className="pq-panel-head"><div><p className="pq-kicker">PROVENANCE</p><h2>EVERY MOVE STAYS.</h2></div><p>Registration, listings, swaps and ownership transfers build the puck’s record.</p></header><div className="pq-history">{mine.flatMap(item=>item.history.map(event=>({...event,item}))).sort((a,b)=>b.at.localeCompare(a.at)).map((event,index)=><article key={`${event.item.id}-${index}`}><span>{new Date(event.at).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span><i/><div><small>{event.item.serial} / {themeById(event.item.themeId).short}</small><h3>{event.event.toUpperCase()}</h3><p>{event.note}</p></div></article>)}</div></section>}
 {revealed&&<div className="pq-reveal" role="dialog" aria-modal="true" aria-label="Puck revealed"><button className="pq-reveal-close" onClick={()=>setRevealed(null)} aria-label="Close reveal"><X/></button><Sparkles/><p>CLAIM VERIFIED</p><MiniPuck themeId={revealed} className="pq-reveal-puck" eager/><h2>{themeById(revealed).name}</h2><span>NOW REGISTERED TO YOUR LOCKER</span><button className="pq-primary" onClick={()=>{setRevealed(null);setTab('collection')}}>View collection <ArrowRight/></button></div>}
 </DashboardShell>
}

export function AdminDashboard(){
 const {session,ready:sessionReady,signOut}=useSession('admin');const {state,update,reset,ready}=useQuest();
 const [section,setSection]=useState<'overview'|'codes'|'designs'|'rewards'|'collectors'>('overview'),[amount,setAmount]=useState(5),[themeId,setThemeId]=useState('random'),[notice,setNotice]=useState('');
 if(!sessionReady||!ready)return <main id="main" className="pq-loading"><span/></main>;if(!session)return <LockedDashboard admin/>;
 const redeemed=state.codes.filter(code=>code.status==='redeemed').length,readyCodes=state.codes.filter(code=>code.status==='ready').length,collectorCount=new Set(state.collectibles.map(item=>item.ownerEmail)).size;
 function token(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',bytes=crypto.getRandomValues(new Uint8Array(8));return Array.from(bytes,(byte,index)=>chars[byte%chars.length]+(index===3?'-':'')).join('')}
 function generate(){const createdAt=new Date().toISOString();update(draft=>{for(let index=0;index<amount;index++){const theme=themeId==='random'?questThemes[(draft.codes.length+index)%questThemes.length].id:themeId;draft.codes.unshift({code:`PQ-E1-${token()}`,themeId:theme,status:'ready',createdAt})}draft.audit.unshift({at:createdAt,event:'codes_generated',detail:`${amount} Edition 01 codes created`})});setNotice(`${amount} single-use codes generated and added to inventory.`)}
 function toggleReward(id:string){update(draft=>{const reward=draft.rewards.find(item=>item.id===id)!;reward.enabled=!reward.enabled;draft.audit.unshift({at:new Date().toISOString(),event:'reward_changed',detail:`${reward.name} ${reward.enabled?'enabled':'disabled'}`})})}
 return <DashboardShell session={session} signOut={signOut} admin><section className="pq-admin-head"><div><p className="pq-kicker">PUCKQUEST OPERATIONS</p><h1>EDITION 01</h1><p>Codes, ownership, collectors and reward controls.</p></div><DemoBadge/></section><nav className="pq-admin-nav">{([['overview','Overview'],['codes','Code inventory'],['designs','Designs'],['rewards','Rewards'],['collectors','Collectors']] as const).map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</nav>{notice&&<div className="pq-notice" role="status">{notice}<button onClick={()=>setNotice('')}><X/></button></div>}
 {section==='overview'&&<section className="pq-admin-panel"><div className="pq-admin-metrics"><article><KeyRound/><small>READY CODES</small><b>{readyCodes}</b><span>AVAILABLE TO PACK</span></article><article><ScanLine/><small>REDEEMED</small><b>{redeemed}</b><span>IMMUTABLE CLAIMS</span></article><article><PackageOpen/><small>REGISTERED PUCKS</small><b>{state.collectibles.length}</b><span>ACROSS DEMO LEDGER</span></article><article><Users/><small>COLLECTORS</small><b>{collectorCount}</b><span>WITH OWNERSHIP</span></article></div><div className="pq-admin-split"><div><h2>RECENT LEDGER EVENTS</h2>{state.audit.slice(0,8).map((event,index)=><article className="pq-audit-row" key={`${event.at}-${index}`}><span>{new Date(event.at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</span><b>{event.event.replaceAll('_',' ')}</b><p>{event.detail}</p></article>)}</div><div className="pq-system-card"><ShieldCheck/><p className="pq-kicker">SERIES INTEGRITY</p><h3>ONE CODE.<br/>ONE CLAIM.</h3><ul><li><Check/>Redeemed codes never return to inventory</li><li><Check/>Transfers move an existing serial</li><li><Check/>Every change adds a ledger event</li><li><Check/>Prize logic separates same-edition and mixed-edition sets</li></ul></div></div></section>}
 {section==='codes'&&<section className="pq-admin-panel"><div className="pq-code-builder"><div><p className="pq-kicker">PACKET CODE GENERATOR</p><h2>CREATE INVENTORY.</h2><p>Each code is assigned to one hidden design before packing. The collector only sees the theme when the packet is opened.</p></div><div><label>QUANTITY<input type="number" min="1" max="25" value={amount} onChange={e=>setAmount(Math.max(1,Math.min(25,Number(e.target.value)||1)))}/></label><label>ASSIGNMENT<select value={themeId} onChange={e=>setThemeId(e.target.value)}><option value="random">Balanced across Edition 01</option>{questThemes.map(theme=><option value={theme.id} key={theme.id}>{theme.name} / {theme.short}</option>)}</select></label><button className="pq-primary" onClick={generate}>Generate codes <KeyRound/></button></div></div><div className="pq-code-table"><div className="pq-table-head"><span>CODE</span><span>HIDDEN DESIGN</span><span>STATUS</span><span>OWNER / DATE</span></div>{state.codes.map(row=><article key={row.code}><code>{row.code}</code><span>{themeById(row.themeId).name}</span><b className={row.status}>{row.status}</b><small>{row.redeemedBy||new Date(row.createdAt).toLocaleDateString()}</small></article>)}</div></section>}
 {section==='designs'&&<section className="pq-admin-panel"><header className="pq-panel-head"><div><p className="pq-kicker">OFFICIAL SUPPLIED ARTWORK</p><h2>32 DESIGNS / FOUR DIVISIONS.</h2></div><p>Every Edition 01 image from George’s supplied PuckQuest bundle is present.</p></header><div className="pq-admin-designs">{questThemes.map(theme=>{const total=state.collectibles.filter(item=>item.themeId===theme.id).length;return <article key={theme.id}><MiniPuck themeId={theme.id}/><div><small>{theme.division} / {theme.conference}</small><h3>{theme.name}</h3><span>{total} REGISTERED</span></div></article>})}</div></section>}
 {section==='rewards'&&<section className="pq-admin-panel"><header className="pq-panel-head"><div><p className="pq-kicker">OFFICIAL REWARD CONTROLS</p><h2>THE PRIZE BOARD.</h2></div><p>These ten tiers mirror Apex’s September 21 contest brief. Pause a tier here without changing the collector ledger or registration history.</p></header><div className="pq-admin-rewards">{state.rewards.map(reward=><article key={reward.id}><span><Gift/><b>{reward.prize}</b></span><div><small>{reward.goal}</small><h3>{reward.name}</h3><p>{reward.description}</p></div><button className={reward.enabled?'on':''} onClick={()=>toggleReward(reward.id)} aria-pressed={reward.enabled}><i/>{reward.enabled?'ACTIVE':'PAUSED'}</button></article>)}</div></section>}
 {section==='collectors'&&<section className="pq-admin-panel"><header className="pq-panel-head"><div><p className="pq-kicker">COLLECTOR DIRECTORY</p><h2>WHO OWNS WHAT.</h2></div><button className="pq-secondary" onClick={()=>{reset();setNotice('Demo ledger reset to the review-ready starting state.')}}><RefreshCw/> Reset demo ledger</button></header><div className="pq-collector-table">{state.users.filter(user=>user.role==='collector').map(user=>{const items=state.collectibles.filter(item=>item.ownerEmail===user.email),unique=new Set(items.map(item=>item.themeId)).size;return <article key={user.email}><span><UserRound/></span><div><b>{user.name}</b><small>{user.email}</small></div><strong>{items.length}<small>PUCKS</small></strong><strong>{unique}<small>UNIQUE</small></strong><i>{items.filter(item=>item.status==='listed').length} LISTED</i></article>})}</div></section>}
 </DashboardShell>
}
