'use client';
import React,{createContext,useContext,useState,useEffect,useRef} from 'react';
import Link from '@/app/components/link';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,ArrowRight,ShoppingBag,Menu,Minus,Plus,Trash2,Check,Truck,Mail,ShieldCheck,X} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetHeader} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {parseCatalogue} from '@/lib/live';
import {PuckSurface} from './physical';
import {products,Product,Variant,nav,money,faqs,ASSETS,MERCHANT,EMAIL} from '@/lib/apex';
import {themeById} from '@/lib/puckquest';
type Line={variantId:string;quantity:number};
type StoreType={cart:Line[];setCart:React.Dispatch<React.SetStateAction<Line[]>>;catalog:Product[];openCart:()=>void;add:(p:Product,v:Variant,q:number)=>void};
const Store=createContext<StoreType>(null!);
export const useStore=()=>useContext(Store);
export function StoreProvider({children}:{children:React.ReactNode}){
 const [cart,setCart]=useState<Line[]>([]),[loaded,setLoaded]=useState(false),[open,setOpen]=useState(false),[catalog,setCatalog]=useState(products);
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('apex-cart-v1')||'[]');if(Array.isArray(x))setCart(x.filter(i=>products.some(p=>p.variants.some(v=>v.id===i.variantId))&&Number.isInteger(i.quantity)&&i.quantity>0&&i.quantity<=99));}catch{}setLoaded(true);const c=new AbortController();fetch('/api/catalogue',{signal:c.signal}).then(async r=>r.ok?parseCatalogue(await r.json()):null).then(d=>{if(d?.products)setCatalog(products.map(p=>({...p,variants:p.variants.map(v=>{const live=d.products.find((x:any)=>x.handle===p.handle)?.variants.find((x:any)=>String(x.id)===v.id);return live?{...v,price:Number(live.price),available:live.available}:v;})})));}).catch(()=>{});return()=>c.abort();},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('apex-cart-v1',JSON.stringify(cart));}catch{}},[cart,loaded]);
 function add(p:Product,v:Variant,q:number){if(!v.available)return;setCart(c=>{const found=c.find(i=>i.variantId===v.id);return found?c.map(i=>i.variantId===v.id?{...i,quantity:Math.min(99,i.quantity+q)}:i):[...c,{variantId:v.id,quantity:q}];});setOpen(true);}
 return <Store.Provider value={{cart,setCart,catalog,openCart:()=>setOpen(true),add}}>{children}<Sheet open={open} onOpenChange={setOpen}><SheetContent className="cart-sheet"><SheetHeader><SheetTitle>Your kit.</SheetTitle><SheetDescription>Your selected Apex pucks. All prices in USD.</SheetDescription></SheetHeader><CartContents close={()=>setOpen(false)}/></SheetContent></Sheet></Store.Provider>;
}
export function Header(){const {cart,openCart}=useStore();const [menu,setMenu]=useState(false);const path=usePathname();const active=(href:string)=>path===href||(href!=='/'&&path.startsWith(`${href}/`));useEffect(()=>{setMenu(false)},[path]);return <><a className="skip" href="#main">Skip to content</a><div className="announcement"><span>ENGINEERED IN AMERICA. MADE IN SRI LANKA.</span><span><Truck size={13}/> FREE US SHIPPING ON GAME & PRO PUCKS</span></div><header className="header"><Link href="/" className="brand" aria-label="Apex Hockey Pucks home"><img src={ASSETS.logo} alt="APEX Hockey Pucks" width="134" height="46"/></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label,href])=><Link key={href} href={href} aria-current={active(href)?'page':undefined}>{label}</Link>)}</nav><div className="header-actions"><Link className="contact-nav" href="/contact">Get in touch <ArrowUpRight size={15}/></Link><button className="cart-trigger" onClick={openCart} aria-label={`Open cart, ${cart.reduce((n,i)=>n+i.quantity,0)} packs`}><ShoppingBag size={20}/><span>{cart.reduce((n,i)=>n+i.quantity,0)}</span></button><button className="mobile-menu icon-button" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button></div></header><Sheet open={menu} onOpenChange={setMenu}><SheetContent className="menu-sheet"><SheetHeader><SheetTitle>APEX / MENU</SheetTitle><SheetDescription>Find your game.</SheetDescription></SheetHeader><nav aria-label="Mobile navigation">{[...nav,['Support & FAQ','/faq'],['Contact','/contact']].map(([label,href],i)=><Link key={href} href={href} aria-current={active(href)?'page':undefined} onClick={()=>setMenu(false)}><small>{String(i+1).padStart(2,'0')}</small>{label}<ArrowUpRight/></Link>)}</nav></SheetContent></Sheet></>}
export function Footer(){return <footer className="footer"><div className="footer-top"><Link href="/" className="brand" aria-label="Apex home"><img src={ASSETS.logo} alt="Apex Hockey Pucks" width="165" height="58"/></Link><p>The game starts here.</p><Link href="/contact" className="text-link">Let’s talk pucks <ArrowUpRight/></Link></div><div className="footer-grid"><div><p className="eyebrow">APEX HOCKEY PUCKS INC.</p><p>820 Grand Blvd.<br/>Deer Park, NY 11729, USA</p><a className="email-link" href={`mailto:${EMAIL}`}>{EMAIL}</a></div><div><h3>THE LINEUP</h3><Link href="/shop">All pucks</Link><Link href="/custom-pucks">Custom logo pucks</Link><Link href="/team-orders">Team & bulk orders</Link><Link href="/puckquest">PuckQuest E1</Link></div><div><h3>APEX</h3><Link href="/manufacturing">Our craft</Link><Link href="/contact?type=Free+sample">Request a sample</Link><a href="https://instagram.com/apexpropucks" target="_blank" rel="noreferrer">Instagram ↗</a><Link href="/contact">Contact us</Link></div><div><h3>SUPPORT</h3><Link href="/faq">Frequently asked questions</Link><Link href="/support/shipping">Shipping & delivery</Link><Link href="/support/returns">Returns & guarantee</Link><Link href="/contact?type=Order+support">Order support</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} APEX HOCKEY PUCKS INC.</span><span><Link href="/support/privacy">Privacy</Link><Link href="/support/terms">Terms</Link><span>USD / UNITED STATES</span></span></div></footer>}
export function Btn({href,children,light=false,outline=false}:{href:string;children:React.ReactNode;light?:boolean;outline?:boolean}){return <Link className={`btn ${light?'light':''} ${outline?'outline':''}`} href={href}>{children}<ArrowUpRight size={18}/></Link>}
export function SelectField({label,value,onChange,options,id}:{label:string;value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];id:string}){return <div className="field"><label id={`${id}-label`}>{label}</label><Select value={value} onValueChange={next=>{if(next)onChange(next)}}><SelectTrigger aria-labelledby={`${id}-label`} className="apex-select"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
export function Quantity({value,onChange,label='Quantity'}:{value:number;onChange:(n:number)=>void;label?:string}){return <div className="quantity" aria-label={label}><button onClick={()=>onChange(Math.max(1,value-1))} disabled={value<=1} aria-label={`Decrease ${label.toLowerCase()}`}><Minus size={16}/></button><input aria-label={label} type="number" min="1" max="99" value={value} onChange={e=>onChange(Math.max(1,Math.min(99,Number(e.target.value)||1)))}/><button onClick={()=>onChange(Math.min(99,value+1))} disabled={value>=99} aria-label={`Increase ${label.toLowerCase()}`}><Plus size={16}/></button></div>}
export function CartContents({close}:{close?:()=>void}){const {cart,setCart,catalog}=useStore();const [error,setError]=useState(''),[checking,setChecking]=useState(false);const lines=cart.flatMap(i=>{const p=catalog.find(p=>p.variants.some(v=>v.id===i.variantId));const v=p?.variants.find(v=>v.id===i.variantId);return p&&v?[{...i,p,v}]:[]});const subtotal=lines.reduce((s,i)=>s+i.quantity*i.v.price,0);
 async function checkout(){setChecking(true);setError('');try{const r=await fetch('/api/catalogue',{cache:'no-store'});if(r.ok){const d=parseCatalogue(await r.json());for(const l of lines){const v=d?.products?.find((p:any)=>p.handle===l.p.handle)?.variants.find((v:any)=>String(v.id)===l.v.id);if(v&&!v.available)throw Error(`${l.p.name} — ${l.v.title} is currently unavailable. Please remove it to continue.`);}}window.location.assign(`${MERCHANT}/cart/${lines.map(i=>`${i.v.id}:${i.quantity}`).join(',')}`);}catch(e){setError(e instanceof Error?e.message:'Could not open checkout. Please try again.');setChecking(false);}}
 if(!lines.length)return <div className="empty-cart"><ShoppingBag size={44}/><h3>Ready for your next shift?</h3><p>Build your kit with game, markless or collectible pucks.</p><Link className="btn" href="/shop" onClick={close}>Explore the lineup <ArrowRight size={18}/></Link></div>;
 return <><div className="cart-lines">{lines.map(i=><article className="cart-line" key={i.v.id}><Link href={`/products/${i.p.handle}`} onClick={close}><img src={i.p.images[0]} alt={i.p.name} width="100" height="100"/></Link><div><Link href={`/products/${i.p.handle}`} onClick={close}>{i.p.name}</Link><p>{i.p.category==='Collectibles'?i.v.title:`${i.v.title}-puck pack`}</p><Quantity value={i.quantity} label={`${i.p.name} pack quantity`} onChange={n=>setCart(c=>c.map(x=>x.variantId===i.v.id?{...x,quantity:n}:x))}/>{!i.v.available&&<p className="error">Currently unavailable</p>}</div><div className="cart-line-end"><strong>{money(i.quantity*i.v.price)}</strong><button aria-label={`Remove ${i.p.name}`} onClick={()=>setCart(c=>c.filter(x=>x.variantId!==i.v.id))}><Trash2 size={17}/></button></div></article>)}</div><div className="cart-summary"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><p>USD. Tax and delivery confirmed at checkout.</p>{error&&<p role="alert" className="error">{error}</p>}<button className="btn full" onClick={checkout} disabled={checking||lines.some(i=>!i.v.available)}>{checking?'Opening checkout…':'Secure checkout'}<ArrowUpRight size={18}/></button><p className="checkout-note"><ShieldCheck size={15}/> Continue to Apex’s existing secure checkout.</p>{close&&<button className="plain-link" onClick={close}>Continue shopping</button>}</div></>;
}
function QuestCardVisual({view}:{view:number}){return <div className={`quest-card-visual view-${view}`}><span className="quest-card-ice" aria-hidden="true"/>{view===0?<><img className="quest-card-pack" src="/assets/puckquest/mini-keytag-pack.webp" alt="Apex mini keytag puck retail pack" width="700" height="1200" loading="lazy"/><span className="quest-card-mini quest-card-mini-one"><img src={themeById('boston').image} alt="Boston Edition 01 printed puck artwork" width="360" height="360" loading="lazy"/></span></>:<div className="quest-card-collection" aria-label="A selection of Edition 01 printed designs">{['kraken','colorado','boston'].map((theme,i)=><span className={`quest-card-mini mini-${i+1}`} key={theme}><img src={themeById(theme).image} alt={`${themeById(theme).name} Edition 01 printed puck artwork`} width="360" height="360" loading="lazy"/></span>)}</div>}<span className="quest-card-stamp">MINI KEYTAG / EDITION 01</span></div>}
export function ProductCard({product:p,index=0}:{product:Product;index?:number}){const {catalog}=useStore();const [angle,setAngle]=useState(0);const live=catalog.find(x=>x.id===p.id)||p;const quest=p.handle==='apex-puckquest-e1',views=quest?2:p.images.length;return <article className={`product-card equipment-card product-${index} ${quest?'quest-product-card':''} ${angle?'is-inspected':''}`}><div className="product-card-visual"><span className="product-number">0{index+1} / {quest?'MINI PUCK COLLECTIBLES':p.category.toUpperCase()}</span>{!live.variants.some(v=>v.available)&&<span className="stock-badge">SOLD OUT</span>}<Link href={`/products/${p.handle}`} className="equipment-card-link" aria-label={`Explore ${p.name}`}>{quest?<QuestCardVisual view={angle}/>:<PuckSurface><img key={angle} src={p.images[angle]} alt={p.title} width="600" height="600" loading="lazy" draggable="false"/></PuckSurface>}<span className="card-equipment-lines" aria-hidden="true"/><span className="card-spec">{quest?(angle===0?'THE PHYSICAL MINI KEYTAG PUCK':'32 EDITION 01 DESIGNS'):p.features[angle%p.features.length]}</span></Link><button className="card-inspect" aria-label={`${quest?'Switch':'Rotate'} ${p.name} product view`} onClick={()=>setAngle((angle+1)%views)}><span>0{angle+1} / 0{views}</span><span>{quest?'VIEW ↔':'ROTATE ↻'}</span></button></div><Link href={`/products/${p.handle}`} className="product-card-info"><div><h3>{p.name}</h3><p>{quest?'Mini keytag collectibles':p.category}</p></div><span><small>FROM</small>{money(Math.min(...live.variants.map(v=>v.price)))}<ArrowUpRight size={18}/></span></Link>{quest&&<Link className="quest-card-enter" href="/puckquest">ENTER PUCKQUEST <ArrowRight size={16}/></Link>}</article>}
export function FAQList({items=faqs}:{items?:typeof faqs}){return <Accordion type="single" collapsible className="faq-list">{items.map((f,i)=><AccordionItem value={String(i)} key={f.q}><AccordionTrigger>{f.q}</AccordionTrigger><AccordionContent>{f.a}</AccordionContent></AccordionItem>)}</Accordion>}
export function PuckMotion({src,alt,className=''}:{src:string;alt:string;className?:string}){return <PuckSurface className={`puck-motion ${className}`}><img src={src} alt={alt} width="1000" height="1000" loading={className.includes('hero')?'eager':'lazy'} draggable="false"/></PuckSurface>}
export function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');o.unobserve(e.target)}}),{threshold:.08});ref.current.classList.add('will-reveal');o.observe(ref.current);return()=>o.disconnect()},[]);return <div ref={ref} className={className}>{children}</div>}
