window.TinTechProducts={
 metal:{kicker:'Existing platform · Pouch caddies',title:'Metal-lid dip cans',description:'A molded plastic base paired with a thin metal snap-on cover for a compact, tactile packaging format.',image:'assets/product-metal.jpg',facts:[['Material','Molded plastic with metal cover'],['Published size','60 mm diameter × 20 mm height'],['Published MOQ','100,000 pieces'],['Development route','Colour, finish, print and production review']]},
 hinged:{kicker:'Existing platform · Pouch caddies',title:'Hinged plastic caddies',description:'An all-plastic round format with an integrated top hinge, secure closure and a platform that can be developed around the product use.',image:'assets/product-hinged.jpg',facts:[['Material','Molded plastic'],['Published size','70 mm diameter × 19 mm height'],['Published MOQ','1,000,000 pieces'],['Development route','Colour, branding and production review']]},
 unhinged:{kicker:'Existing platform · Pouch caddies · TUP 000',title:'Unhinged plastic caddies',description:'An all-plastic round caddy with a removable lid. Review closure fit, material and finish against the intended product and use.',image:'assets/product-plastic.jpg',facts:[['Material','Molded plastic'],['Published size','70 mm diameter × 19 mm height'],['Published MOQ','1,000,000 pieces'],['Closure','Separate removable lid']]},
 colour:{kicker:'Existing platform · Pouch caddies · MCP 002',title:'Colour-match metal-lid caddies',description:'A molded plastic base and precision-fit metal snap-on cover, developed as a coordinated colour and finish program.',image:'assets/product-colour.jpg',facts:[['Material','Plastic with metal cover'],['Published size','60 mm diameter × 20 mm height'],['Published MOQ','100,000 pieces'],['Development route','Colour, finish and production review']]},
 cups:{kicker:'Packaging systems',title:'Cups & lids',description:'Rigid cups and matched lid systems developed around the product, seal, use case, packing route and shelf presentation.',image:'assets/catalog-cups.webp',facts:[['Formats','Short, tall and application-specific'],['Lid routes','Plastic or sourced metal components'],['Branding','Colour, molded detail, print and labels'],['Starting point','Sample, drawing or functional brief']]},
 containers:{kicker:'Packaging systems',title:'Containers & closures',description:'Rigid containers, jars, caps and closure systems designed as a connected product rather than unrelated components.',image:'assets/catalog-containers.webp',facts:[['Applications','Consumer, industrial and private label'],['Components','Bodies, caps, lids, closures and inserts'],['Materials','Selected around performance and production'],['Starting point','Existing format or custom development']]},
 retail:{kicker:'Retail & apparel',title:'Hangers, hooks & clips',description:'Molded retail components developed around load, presentation, handling, repeatability and commercial volume.',image:'assets/catalog-retail.webp',facts:[['Range','Hangers, hooks, clips and display parts'],['Development','Existing reference or new geometry'],['Finishes','Material colour and molded branding'],['Program','Tooling through repeat production']]},
 components:{kicker:'Custom components',title:'Housings, fittings & molded parts',description:'Made-to-spec plastic parts for products that need a precise geometry, mechanical relationship or repeatable manufacturing route.',image:'assets/catalog-components.webp',facts:[['Range','Housings, fittings, clips, covers and parts'],['Inputs','Sample, drawing, CAD or functional requirement'],['Route','Design review, tooling, trials and approval'],['Output','Controlled recurring production']]},
 program:{kicker:'Production programs',title:'Your tooling. Your production line.',description:'A path from supply into client-owned molds, reserved capacity and dedicated production planning as the program grows.',image:'assets/catalog-production.webp',facts:[['Start','Existing format or approved new design'],['Asset','Dedicated tooling where required'],['Scale','Forecast-led capacity planning'],['Execution','Production, packing and delivery coordination']]}
};

window.TinTechPathways={
 supply:{name:'Existing product supply',rows:[['Best for','An existing format with a practical first production route'],['Your starting point','Product format, quantity, finish and delivery destination'],['We agree','Product specification, samples, commercial terms and packing'],['Next step','Review the product and confirm the production brief']]},
 tooling:{name:'Client-owned tooling',rows:[['Best for','A product with its own geometry or dedicated mold'],['Your starting point','Sample, drawing, CAD or functional brief'],['We agree','Tooling investment, ownership, maintenance and production rights'],['Next step','Confirm the drawing, mold route and sample approval plan']]},
 capacity:{name:'Reserved capacity',rows:[['Best for','Recurring orders with forecast demand'],['Your starting point','An approved product and expected delivery rhythm'],['We agree','Capacity allocation, order schedule and quality checkpoints'],['Next step','Review the forecast and build a production calendar']]},
 line:{name:'Dedicated line',rows:[['Best for','A long-term program that needs its own production system'],['Your starting point','Volume plan, product scope and manufacturing requirements'],['We agree','Equipment, operating responsibilities, capacity and investment'],['Next step','Review the dedicated line or Sri Lanka factory pathway']]}
};
