
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const navToggle=$('.nav-toggle'),siteNav=$('header nav'),navLabel=navToggle?.textContent.trim()||'Menu';function syncPageLock(){document.body.classList.toggle('overlay-open',document.body.classList.contains('nav-open')||document.body.classList.contains('cart-open'))}function closeNav(){siteNav?.classList.remove('open');document.body.classList.remove('nav-open');navToggle?.setAttribute('aria-expanded','false');if(navToggle)navToggle.textContent=navLabel;syncPageLock()}navToggle?.addEventListener('click',()=>{const open=!siteNav?.classList.contains('open');siteNav?.classList.toggle('open',open);document.body.classList.toggle('nav-open',open);navToggle.setAttribute('aria-expanded',String(open));navToggle.textContent=open?'Close':navLabel;syncPageLock()});$$('header nav a').forEach(link=>link.addEventListener('click',closeNav));
const brand=document.documentElement.dataset.brand||'site',cartKey='aquanix-cart-v3-'+brand;let cart;try{cart=JSON.parse(localStorage.getItem(cartKey)||'[]');if(!Array.isArray(cart))cart=[]}catch{cart=[]}const drawer=$('[data-cart]'),scrim=$('[data-scrim]');
function renderCart(){const box=$('[data-cart-lines]');const count=cart.reduce((n,x)=>n+(x.qty||1),0);$$('[data-count]').forEach(x=>x.textContent=count);if(!box)return;box.innerHTML=cart.length?cart.map((x,i)=>'<div class="cart-line"><div><b>'+x.name+'</b><small>'+(x.kind==='nutrition'?'Nutrition':x.kind==='plan'?'Saved plan':'Livestock')+' · '+'Concept selection · not quoted'+'</small><div class="cart-qty"><button data-qty="-1" data-index="'+i+'" aria-label="Decrease quantity">−</button><span>'+(x.qty||1)+'</span><button data-qty="1" data-index="'+i+'" aria-label="Increase quantity">+</button></div></div><button data-remove="'+i+'">Remove</button></div>').join(''):'<p>Your list is empty.</p>';const total=cart.reduce((n,x)=>n+x.price*(x.qty||1),0);$('[data-total]').textContent='Not quoted';if($('[data-checkout]'))$('[data-checkout]').disabled=!cart.length;localStorage.setItem(cartKey,JSON.stringify(cart));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);renderCart()});$$('[data-qty]').forEach(b=>b.onclick=()=>{const x=cart[+b.dataset.index];x.qty=Math.max(1,(x.qty||1)+(+b.dataset.qty));renderCart()})}
let cartOpener;function openCart(){closeNav();cartOpener=document.activeElement;drawer?.classList.add('open');drawer?.setAttribute('aria-hidden','false');scrim?.classList.add('open');document.body.classList.add('cart-open');syncPageLock();$('[data-cart-close]')?.focus()};function closeCart(){const wasOpen=drawer?.classList.contains('open');drawer?.classList.remove('open');drawer?.setAttribute('aria-hidden','true');scrim?.classList.remove('open');document.body.classList.remove('cart-open');syncPageLock();if(wasOpen&&cartOpener instanceof HTMLElement)cartOpener.focus()}
function addToCart(button){let name=button.dataset.name,kind=button.dataset.kind||'livestock';if(kind==='nutrition'){const size=$('[data-size-choice].selected')?.textContent?.trim();if(size)name+=' — '+size}const existing=cart.find(x=>x.name===name&&x.kind===kind);if(existing)existing.qty=(existing.qty||1)+1;else cart.push({name,price:+button.dataset.price||0,kind,qty:1});renderCart();openCart()}
$('.bag')?.addEventListener('click',openCart);$('[data-cart-close]')?.addEventListener('click',closeCart);scrim?.addEventListener('click',closeCart);$$('[data-add],[data-interest]').forEach(b=>b.onclick=()=>addToCart(b));renderCart();
const dialog=$('dialog');$('[data-checkout]')?.addEventListener('click',()=>{if(!cart.length||!dialog)return;let list=dialog.querySelector('.proposal-review-list');if(!list){list=document.createElement('pre');list.className='proposal-review-list';dialog.querySelector('p')?.after(list)}list.textContent=cart.map(x=>(x.qty||1)+' × '+x.name).join('\n');dialog.showModal()});$$('[data-dialog-close]').forEach(b=>b.onclick=()=>dialog?.close());
const input=$('[data-search-input]');function filter(){const q=(input?.value||'').toLowerCase();let n=0;$$('[data-product]').forEach(c=>{const ok=(c.dataset.search||c.innerText).toLowerCase().includes(q);c.hidden=!ok;if(ok)n++});if($('[data-result-count]'))$('[data-result-count]').textContent=n+' records'}input?.addEventListener('input',filter);if(input)filter();$$('[data-term]').forEach(b=>b.onclick=()=>{input.value=b.dataset.term;filter();input.scrollIntoView({behavior:'smooth'})});
$$('[data-size-choice]').forEach(b=>b.onclick=()=>{$$('[data-size-choice]').forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-pressed','false')});b.classList.add('selected');b.setAttribute('aria-pressed','true')});
$$('[data-gallery-view]').forEach(b=>b.onclick=()=>{$$('[data-gallery-view]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const img=$('.commercial-gallery>img');if(img)img.style.objectPosition=b.dataset.galleryView});

function riftPlan(){const vals=Object.fromEntries($$('[data-builder] input:checked').map(x=>[x.name,x.value]));if(!vals.lake)return null;const habitat=vals.shore==='Rock face'?'Rock structure with broken sight lines':vals.shore==='Shell bed'?'Shell field with clear compact territories':'Open swimming room with a restrained hardscape';const guide=vals.inhabitants==='Empty tank'?'Build the habitat first, then select one compatible starting group.':'Review every established inhabitant before adding a new territory or social group.';$('[data-builder-title]').textContent=[vals.lake,vals.shore,vals.volume].join(' / ').toUpperCase();$('[data-rift-habitat]').textContent=habitat;$('[data-rift-guidance]').textContent=guide+' Desired behavior: '+vals.behavior+'. Experience: '+vals.experience+'.';$('[data-rift-note]').textContent="Proposed field note: locality narrows the question; adult size and behavior still decide the answer.";return vals}
$$('[data-builder] input').forEach(i=>i.onchange=riftPlan);if($('[data-builder]'))riftPlan();$('[data-save-rift]')?.addEventListener('click',()=>{localStorage.setItem('aquanix-rift-v3',JSON.stringify(riftPlan()));$('[data-save-state]').textContent='Rift plan saved on this device.'});

const arrivalKey='aquanix-arrival-v3';let arrival,arrivalTicker;try{arrival=JSON.parse(localStorage.getItem(arrivalKey)||'{"steps":{}}');if(!arrival||typeof arrival.steps!=='object'||!arrival.steps)arrival={steps:{}}}catch{arrival={steps:{}}}function renderArrival(){const buttons=$$('[data-arrival-step]');buttons.forEach(b=>{const done=!!arrival.steps[b.dataset.arrivalStep];b.classList.toggle('done',done);if(b.dataset.arrivalStep!=='temperature')b.querySelector('i').textContent=done?'DONE':'MARK DONE';b.setAttribute('aria-pressed',String(done))});const done=Object.values(arrival.steps).filter(Boolean).length,total=buttons.length;if($('[data-arrival-count]'))$('[data-arrival-count]').textContent=done+' / '+total+' COMPLETE';if($('[data-arrival-progress]'))$('[data-arrival-progress]').style.width=(total?done/total*100:0)+'%';localStorage.setItem(arrivalKey,JSON.stringify(arrival))}function renderTimer(){if(!arrival.timerStarted)return;const seconds=Math.max(0,Math.floor((Date.now()-arrival.timerStarted)/1000)),m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');if($('[data-timer-value]'))$('[data-timer-value]').textContent=m+':'+s}$$('[data-arrival-step]').forEach(b=>b.onclick=()=>{const key=b.dataset.arrivalStep;if(key==='temperature'&&!arrival.timerStarted){arrival.timerStarted=Date.now();arrivalTicker=setInterval(renderTimer,1000);renderTimer()}else arrival.steps[key]=!arrival.steps[key];renderArrival()});if(arrival.timerStarted){arrivalTicker=setInterval(renderTimer,1000);renderTimer()}renderArrival();$('[data-reset-arrival]')?.addEventListener('click',()=>{arrival={steps:{}};clearInterval(arrivalTicker);renderArrival();if($('[data-timer-value]'))$('[data-timer-value]').textContent='START'});

const zones={Ponds:['Outdoor scale, daily water management and the physical reality behind the livestock catalog.','/fish/'],Greenhouses:['Controlled systems create a different view of breeding, growth and seasonal consistency.','/fish/'],'Breeding systems':['Hands, water and observation turn variety into repeatable husbandry.','/fish/'],'Feed room':['A practical bridge from farm-scale use to a coherent retail product family.','/feed-room/'],Shipping:['The final farm system prepares livestock for the transition from this water to yours.','/shipping/']};$$('[data-zone]').forEach((b,i)=>b.onclick=()=>{const film=$('.farm-film');$$('[data-zone]').forEach(x=>x.classList.remove('active'));$$('.farm-sequence li').forEach((x,n)=>x.classList.toggle('active',n===i));b.classList.add('active');film?.classList.add('changing');setTimeout(()=>{const img=$('[data-zone-image]');if(img)img.src=b.dataset.zoneImageSrc;$('[data-zone-title]').textContent=b.dataset.zone;$('[data-zone-copy]').textContent=zones[b.dataset.zone][0];$('[data-zone-link]').href=zones[b.dataset.zone][1];$('[data-zone-number]').textContent=String(i+1).padStart(2,'0')+' / 05';film?.classList.remove('changing')},220)});

const communityFishArt={
  'Ember Tetra':'/assets/builder-ember-tetra.webp',
  'Common Otocinclus':'/assets/builder-common-otocinclus.webp',
  'Chili Rasbora':'/assets/builder-chili-rasbora.webp',
  'Cardinal Tetra':'/assets/builder-cardinal-tetra.webp'
};
function buildCommunity(){const checks=$$('[data-community] input[type="checkbox"]:checked'),cloud=$('[data-fish-cloud]'),list=$('[data-community-list]'),tank=$('.community-tank');if(!cloud)return null;cloud.innerHTML=checks.map((x,i)=>'<figure class="tank-fish tank-fish-'+(i+1)+'"><img src="'+communityFishArt[x.value]+'" alt="'+x.value+' shown as a concept school in the planted tank"></figure>').join('');tank.classList.toggle('has-fish',checks.length>0);$('[data-tank-verdict]').textContent=checks.length?'THIS COULD BE YOUR TANK.':'EMPTY TANK / READY';list.innerHTML=checks.length?checks.map(x=>'<div><b>'+x.value+'</b><span>'+x.dataset.role+' · quantity to confirm</span></div>').join(''):'<p>No fish selected yet.</p>';const compatibility=$('[data-compatibility]');compatibility.textContent=checks.length===0?'Compatibility review waiting':'Species compatibility not assessed — staff review required';return {tank:$('[data-community] select[name="tank"]').value,movement:$('[data-community] select[name="movement"]').value,plants:$('[data-community] select[name="plants"]').value,fish:checks.map(x=>({name:x.value,role:x.dataset.role}))}}
$('[data-community-build]')?.addEventListener('click',buildCommunity);if($('[data-community]'))buildCommunity();$('[data-save-community]')?.addEventListener('click',()=>{const plan=buildCommunity();localStorage.setItem('aquanix-community-v3',JSON.stringify(plan));$('[data-community-state]').textContent='Tank saved on this device.'});
let savedCommunity;try{savedCommunity=JSON.parse(localStorage.getItem('aquanix-community-v3')||'null');if(!Array.isArray(savedCommunity?.fish))savedCommunity=null}catch{savedCommunity=null}if(savedCommunity&&$('[data-my-tank-status]')){$('[data-my-tank-name]').textContent=savedCommunity.tank+' · '+savedCommunity.plants+' · '+savedCommunity.movement;$('[data-my-tank-status]').textContent=savedCommunity.fish.length+' candidate species saved for staff review.';$('[data-saved-fish]').innerHTML=savedCommunity.fish.map(x=>'<span>'+x.name+' · '+x.role+'</span>').join('')}

$$('[data-share-plan]').forEach(b=>b.onclick=async()=>{const text=$('[data-builder-title]')?.textContent||($('[data-tank-verdict]')?.textContent+' '+($('[data-community-list]')?.innerText||''));try{await navigator.clipboard.writeText(text+' — '+location.href);b.textContent='COPIED'}catch{b.textContent='COPY UNAVAILABLE'}});
function openPrivate(){location.href='/owner/'}$('[data-private-entry]')?.addEventListener('dblclick',openPrivate);document.addEventListener('keydown',e=>{if(e.altKey&&e.shiftKey&&e.key.toLowerCase()==='o')openPrivate();if(e.key==='Escape'){closeNav();closeCart();if(dialog?.open)dialog.close()}});

// Keep keyboard navigation inside an open discussion-list drawer.
document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!drawer?.classList.contains('open')||dialog?.open)return;const focusable=[...drawer.querySelectorAll('button:not([disabled]),a[href]')];const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}});
