import raw from './catalogue.json';
// Keep canonical links and shared PuckQuest merchandising aligned with the Vercel production release.
export const ORIGIN = 'https://apex-hockey-pucks-rebuilt.vercel.app';
export const MERCHANT = 'https://apexhockeypucks.com';
export const EMAIL = 'apexpropucks@gmail.com';
export const ASSETS = {
 logo: '/assets/logo.svg', hero: '/assets/hero-puck.webp', action: '/assets/action.webp', custom: '/assets/custom.webp',
};
export type Variant = {id:string;title:string;price:number;available:boolean};
export type Product = {id:number;handle:string;title:string;name:string;category:string;tag:string;intro:string;description:string;features:string[];images:string[];variants:Variant[]};
const copy: Record<string, Omit<Product,'id'|'handle'|'title'|'images'|'variants'>> = {
 'apex-practice-pucks': {name:'APEX GAME',category:'Game & practice',tag:'EVERY SHIFT. EVERY SESSION.',intro:'The everyday workhorse. Made for the game.',description:'A dependable puck for game night and the work that gets you there. Tight knurling supports confident stick handling, with a dedicated manufacturing process focused on consistency and durability.',features:['Game and practice use','Tight knurled edge','Laboratory tested','Made in Sri Lanka']},
 'apex-pro-markless-ice-hockey-pucks': {name:'APEX PRO',category:'Markless performance',tag:'THE MARKLESS ADVANTAGE.',intro:'Make an impact. Leave the scuffs behind.',description:'Apex’s markless puck brings a rink-focused finish to its professional range. Built with tight knurling for puck control and laboratory-tested for consistency.',features:['Markless rubber formulation','Tight knurled edge','Laboratory tested','Made in Sri Lanka']},
 'apex-puckquest-e1': {name:'PUCKQUEST E1',category:'Collectibles',tag:'OPEN. REVEAL. CLAIM.',intro:'The mini keytag puck with a permanent story.',description:'A sealed mystery-pack collection built around Apex’s mini keychain-style puck. Reveal one of 32 original team-inspired Edition 01 designs, enter the packet’s one-time code and register that physical collectible to your PuckQuest locker.',features:['Mini keytag-style collectible','32 original team themes','50 first-edition pucks per theme','One-time claim and ownership history']},
};
export const products:Product[]=raw.map(p=>({...p,...copy[p.handle],images:p.handle==='apex-puckquest-e1'?['/assets/puckquest/mini-keytag-pack.webp','/assets/puckquest/art/boston-1800x1800.webp','/assets/puckquest/art/kracken-1800x1800.webp']:p.images.slice(0,3).map((_,i)=>`/assets/${p.handle}-${i}.webp`)})).sort((a,b)=>['apex-practice-pucks','apex-pro-markless-ice-hockey-pucks','apex-puckquest-e1'].indexOf(a.handle)-['apex-practice-pucks','apex-pro-markless-ice-hockey-pucks','apex-puckquest-e1'].indexOf(b.handle));
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
export const faqs = [
 {group:'Products',q:'Which Apex puck should I choose?',a:'Choose APEX Game for regular game and practice use. Choose APEX PRO if you need the markless formulation. PuckQuest E1 is a collectible mystery-puck game. For printed team or event pucks, start with Custom Pucks.'},
 {group:'Products',q:'What pack sizes are available?',a:'APEX Game comes in packs of 12, 50 and 100. APEX PRO is listed in packs of 50 and 100. PuckQuest offers League, Conference and Division packs. Select a product to see its pack prices and current availability.'},
 {group:'Products',q:'Where are Apex pucks made?',a:'Apex Hockey Pucks Inc. is American owned and operated in New York. Its pucks are engineered in America and manufactured in a dedicated hockey-puck facility in Sri Lanka.'},
 {group:'Custom printing',q:'What artwork do you need for custom pucks?',a:'Send camera-ready vector artwork as AI, CDR or EPS. Convert text to outlines or curves, or supply the fonts. The published production guidelines do not accept raster artwork such as JPG or PNG. You can use a PNG or JPG in our visual preview, but you will still need to email the production vector file.'},
 {group:'Custom printing',q:'Are there setup or artwork fees?',a:'Apex lists no plate, setup or color-matching fees. Acceptable camera-ready artwork carries no artwork fee. Editing, adjustments or formatting may need a separate quote.'},
 {group:'Custom printing',q:'Can I see a sample before ordering?',a:'Yes. Apex offers a free puck printed with its own logo so you can check the puck and print quality before ordering custom pucks. Request a sample through Contact. Availability and delivery arrangements are confirmed by Apex.'},
 {group:'Custom printing',q:'Will a printed logo wear on the ice?',a:'Ice, sticks and skates are abrasive, so ink can wear over time. Apex uses its own ink blend for print durability. Ask for a sample to evaluate the finish for your intended use.'},
 {group:'Team orders',q:'Can teams, colleges and leagues order in bulk?',a:'Yes. Standard packs can be ordered through the shop. For larger quantities, custom designs, delivery dates or recurring orders, send a team-order request. Apex also publishes special college and pro-team pricing by inquiry.'},
 {group:'Delivery & returns',q:'Is US shipping free?',a:'The current Game and Pro product pages advertise free shipping within the USA. Contact Apex about Canada, other destinations and time-sensitive orders. Shipping and tax details are confirmed at checkout.'},
 {group:'Delivery & returns',q:'Can I return custom printed pucks?',a:'Custom printed orders are not returnable or refundable under Apex’s published contact-page policy. Request the free Apex-logo sample before placing a custom order.'},
 {group:'Delivery & returns',q:'How does the money-back guarantee work?',a:'Apex’s contact page advertises a 14-day money-back guarantee from delivery for eligible pucks and an emailed return label. Its separate legacy refund page states 30 days from purchase for undamaged goods. Contact Apex with your order number to confirm the applicable terms before returning anything.'},
 {group:'Delivery & returns',q:'How do I track an order or get help?',a:'Use the tracking link in your order email. For further help, email apexpropucks@gmail.com with your order number and the email address used at checkout.'},
 {group:'PuckQuest',q:'How do PuckQuest mystery packs work?',a:'A $15 League Pack contains two random themes from across the league. A $20 Conference Pack contains two random themes from your selected conference. A $15 Division Pack contains one random theme from your selected division. Every physical mini puck carries a one-time packet code for registration.'},
 {group:'PuckQuest',q:'When does the PuckQuest speed clock begin?',a:'The clock begins when you register your first puck from a specific edition. Complete all 32 teams from that same edition within 30, 60 or 90 calendar days to qualify for the corresponding speed bonus. Only one speed bonus may be claimed per edition.'},
 {group:'PuckQuest',q:'Can a registered PuckQuest puck be traded or sold?',a:'Yes. The original packet code remains permanently consumed, while the registered serial can move to a new owner through the transfer flow. The ownership history stays with the physical collectible.'},
];
export const nav=[['Shop pucks','/shop'],['Custom pucks','/custom-pucks'],['Team & bulk','/team-orders'],['PuckQuest','/puckquest'],['Our craft','/manufacturing']];
