import Link from '@/app/components/link';
import {notFound} from 'next/navigation';
const content:Record<string,{title:string;intro:string;sections:{h:string;p:string}[];source:string}>={
 shipping:{title:'Shipping & delivery',intro:'Plan your order with the right destination and timing.',sections:[{h:'US delivery',p:'The current APEX Game and APEX PRO product listings advertise free shipping within the United States. Your final delivery options and tax are shown at Apex checkout.'},{h:'Canada and other destinations',p:'Apex’s legacy shipping page mentions Canada. Confirm current coverage and any charges with Apex before ordering outside the USA.'},{h:'Time-sensitive or custom orders',p:'Include your destination, quantity and requested in-hand date in your quote request. Custom production and shipping schedules need direct confirmation; no delivery date is guaranteed by this site.'},{h:'Tracking your order',p:'Check your order and shipping confirmation emails for tracking. If you need help, contact Apex with your order number.'}],source:'https://apexhockeypucks.com/pages/policies#shipping'},
 returns:{title:'Returns & guarantee',intro:'Check the terms for your product before starting a return.',sections:[{h:'The published guarantee',p:'Apex’s contact page describes a 14-day money-back guarantee from delivery and an emailed return label for eligible purchases.'},{h:'A separate legacy refund policy',p:'The older policy page describes a 30-calendar-day return window from purchase for goods received back in unchanged, undamaged condition. Because these pages differ, ask Apex which terms apply to your order.'},{h:'Custom printed pucks',p:'Custom printed orders are not returnable or refundable under the contact-page policy. Apex offers a free puck printed with its logo to help you evaluate the puck and print quality beforehand.'},{h:'Start with your order details',p:'Email apexpropucks@gmail.com with your order number, delivery date and the issue. Obtain return instructions before sending products back.'}],source:'https://apexhockeypucks.com/pages/contact#guarantee'},
 privacy:{title:'Privacy information',intro:'Understand what happens to your information here and at checkout.',sections:[{h:'Your cart',p:'This site saves product identifiers and pack quantities in your browser so the cart can remain available on this device. Removing cart items or clearing your browser’s site data removes that local information.'},{h:'Design previews and inquiry details',p:'Uploaded preview images are processed in your browser and are not uploaded to an Apex server. Inquiry fields stay in the current page while you prepare your request. The email button passes your draft to your chosen email application; you decide whether to send it. Production artwork must be attached there.'},{h:'Checkout',p:'Purchases continue to Apex’s existing store. Apex and its payment providers handle the information required for your order. Review the merchant’s published privacy terms before providing checkout information.'},{h:'Site delivery',p:'Hosting infrastructure processes requests needed to serve the website. This site does not add advertising pixels or marketing cookies. Third-party websites linked here apply their own policies.'},{h:'Privacy questions',p:'Contact Apex at apexpropucks@gmail.com about information supplied to its business. The linked merchant policy contains its full published terms.'}],source:'https://apexhockeypucks.com/pages/policies#privacy'},
 terms:{title:'Terms & ordering',intro:'A clear guide to using this site and placing an Apex order.',sections:[{h:'Product information and prices',p:'Prices are displayed in US dollars. Product and stock information is based on the Apex catalogue, with a live availability check where accessible. Final availability, charges and order acceptance are confirmed by the merchant at checkout.'},{h:'Custom and bulk inquiries',p:'A design preview or request is not an order, accepted proof or confirmed quote. Apex must confirm artwork, print options, quantity, pricing and delivery arrangements directly.'},{h:'Artwork',p:'Only provide designs you own or are authorized to use. The online preview is illustrative and does not establish final print dimensions, ink colors or production suitability.'},{h:'Existing orders and merchant terms',p:'Apex Hockey Pucks Inc. handles purchases, fulfillment and customer support. Its full published terms and policies apply to merchant transactions and are linked below.'},{h:'Names and trademarks',p:'Apex brand assets belong to their respective owners. References to hockey standards or team-inspired collectibles do not imply league affiliation or endorsement.'}],source:'https://apexhockeypucks.com/pages/policies#terms'}
};
export async function generateMetadata({params}:{params:Promise<{topic:string}>}){const {topic}=await params;const c=content[topic];return {title:c?.title||'Support',description:c?.intro,alternates:{canonical:`/support/${topic}`}}}
export function generateStaticParams(){return Object.keys(content).map(topic=>({topic}))}
export default async function Page({params}:{params:Promise<{topic:string}>}){const {topic}=await params;const c=content[topic];if(!c)notFound();return <main id="main" className="section support-page"><aside><p className="eyebrow">APEX SUPPORT</p>{Object.entries(content).map(([k,v])=><Link aria-current={k===topic?'page':undefined} key={k} href={`/support/${k}`}>{v.title}</Link>)}<Link href="/faq">Frequently asked questions</Link><Link href="/contact">Contact Apex ↗</Link></aside><article><p className="eyebrow">ORDER WITH CONFIDENCE</p><h1>{c.title}</h1><p className="support-intro">{c.intro}</p>{c.sections.map(s=><section key={s.h}><h2>{s.h}</h2><p>{s.p}</p></section>)}<a className="text-link" href={c.source} target="_blank" rel="noreferrer">Read Apex’s published policy ↗</a></article></main>}
